#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" member-polling.XXXXXX)
trap 'rm -rf "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze \
  reference-tools/views/member_panel/polling.rb > "$WORK/corpus.json"
if [ "${1:-}" = --check ]; then
  cmp "$WORK/corpus.json" vectors/member-polling.json
  echo 'member polling Rails fixtures: committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/member-polling.json
fi
