[package]
name = "campfire_messages"
version = "0.1.0"
edition.workspace = true

[dependencies]
campfire_runtime.workspace = true
campfire_presentation.workspace = true
rails_compat.workspace = true
campfire_kit.workspace = true
campfire_routes.workspace = true
campfire_db.workspace = true
campfire_richtext.workspace = true
campfire_storage.workspace = true
campfire_views.workspace = true
campfire_app.workspace = true
campfire_web.workspace = true
campfire_channels.workspace = true
anyhow.workspace = true
serde_json.workspace = true
jiff.workspace = true
tracing.workspace = true
askama.workspace = true
