#!/usr/bin/env python3
"""Re-record read-only budget and event model contracts from pinned Rails."""
from pathlib import Path
import os,subprocess
root=Path(__file__).resolve().parents[3];scratch=root/'.scratch'
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE='triage-reference-d7c7de92')
for name in ['budget_usage_contract','event_model_contract']:
 out=scratch/(name+'-verified.json')
 with out.open('wb') as stdout,(scratch/(name+'-verified.log')).open('wb') as stderr:
  subprocess.run(['rust/parity/bin/reference','runner','--seed','default',f'rust/reference-tools/agents/{name}.rb'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
 assert out.read_bytes()==(root/f'rust/vectors/agents_{name}.json').read_bytes(),name
print('WS11 ledger Rails oracles: 2 regenerated byte-identical budget/event model vectors')
