#!/usr/bin/env python3
"""Observe actual pinned Rails transaction-record callbacks and a process-stop gap."""

from pin_identity import PIN, PIN_FULL, PIN_IMAGE
from pathlib import Path
import json,os,shutil,subprocess
root=Path(__file__).resolve().parents[3]
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE=PIN_IMAGE)
base=['rust/parity/bin/reference','runner']
out=root/'.scratch/r4-verified-callbacks.json'
with out.open('wb') as stdout,(root/'.scratch/r4-verified-callbacks.log').open('wb') as stderr:
 subprocess.run(base+['--seed','default','-e','RAILS_LOG_LEVEL=fatal','rust/reference-tools/agents/deletion_callback_contract.rb'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
assert out.read_bytes()==(root/'rust/vectors/agents_deletion_callback_contract.json').read_bytes()
for webhook in ['false','true']:
 results=json.loads(out.read_bytes())['results']
 assert results['created_same_transaction_'+webhook]['polled']==['A','B']
 assert results['updated_first_'+webhook]['polled']==['A edited','B']
 assert results['savepoint_'+webhook]['polled']==['A edited','B']
assert results['first_ledger_failure']['polled']==[]
storage=root/'.scratch/r4-verified-crash-storage'
if storage.exists(): shutil.rmtree(storage)
shutil.copytree(root/'rust/parity/.seed/default/db',storage/'db')
shutil.copytree(root/'rust/parity/.seed/default/storage',storage/'storage')
cmd=base+['--storage',str(storage),'-e','RAILS_LOG_LEVEL=fatal','rust/reference-tools/agents/deletion_crash_contract.rb']
with (root/'.scratch/r4-verified-crash-stop.log').open('wb') as log:
 stopped=subprocess.run(cmd+['stop'],cwd=root,env=env,stdout=log,stderr=log)
assert stopped.returncode==73
out=root/'.scratch/r4-verified-crash.json'
with out.open('wb') as stdout,(root/'.scratch/r4-verified-crash-restart.log').open('wb') as stderr:
 subprocess.run(cmd+['restart'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
assert out.read_bytes()==(root/'rust/vectors/agents_deletion_crash_contract.json').read_bytes()
assert json.loads(out.read_bytes())['results']==dict(thread_exists=False,deletion_events=0,polled_deletions=0)
print(f'WS11 r4 Rails callbacks: 8 registration-order/savepoint cases and stop-on-error regenerated byte-identical ({PIN})')
print(f'WS11 r4 Rails crash: exit=73; restarted process sees deleted thread and zero events ({PIN})')
