#!/usr/bin/env python3
"""Regenerate real destroy, mention and cable effects from pinned Rails."""

from pin_identity import PIN, PIN_FULL, PIN_IMAGE
from pathlib import Path
import os,subprocess
root=Path(__file__).resolve().parents[3];scratch=root/'.scratch'
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE=PIN_IMAGE)
for name in ['account_removal_contract','approval_neighbour_contract','stream_frames_contract']:
 out=scratch/(name+'-verified.json')
 with out.open('wb') as stdout,(scratch/(name+'-verified.log')).open('wb') as stderr:
  subprocess.run(['rust/parity/bin/reference','runner','--seed','default',f'rust/reference-tools/agents/{name}.rb'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
 assert out.read_bytes()==(root/f'rust/vectors/agents_{name}.json').read_bytes(),name
print('WS11 peer Rails oracles: 2 destroy outcomes, 1 approval/mention neighbour and 3 rendered cable phases regenerated byte-identical')
