#!/usr/bin/env python3
"""Re-record delivery and shared-reader transcripts with the pinned Rails app."""
from pathlib import Path
import os,subprocess
root=Path(__file__).resolve().parents[3];scratch=root/'.scratch';scratch.mkdir(exist_ok=True)
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE='triage-reference-d7c7de92')
for name in ['webhook_paths_contract','repository_adapter_contract']:
 out=scratch/(name+'-verified.json')
 with out.open('wb') as stdout,(scratch/(name+'-verified.log')).open('wb') as stderr:
  subprocess.run(['rust/parity/bin/reference','runner','--seed','default',f'rust/reference-tools/agents/{name}.rb'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
 assert out.read_bytes()==(root/f'rust/vectors/agents_{name}.json').read_bytes(),name
print('WS11 delivery path Rails oracle: 10 raw webhook and 5 repository read/redaction transcripts regenerated byte-identical')
