"""Pin the merge's Calendar failure boundary, including the jobs Rails never enqueues."""

from pin_identity import PIN, PIN_FULL, PIN_IMAGE
from pathlib import Path
import hashlib,json,os,subprocess
root=Path(__file__).resolve().parents[3]
out=root/'.scratch/r4-event-callback-failure-verified.json'
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE=PIN_IMAGE)
with out.open('wb') as stdout,(root/'.scratch/r4-event-callback-failure-verified.log').open('wb') as stderr:
 subprocess.run(['rust/parity/bin/reference','runner','--seed','first_run','-e','RAILS_LOG_LEVEL=fatal','rust/reference-tools/agents/event_callback_failure_contract.rb'],cwd=root,env=env,stdout=stdout,stderr=stderr,check=True)
assert out.read_bytes()==(root/'rust/vectors/agents_event_callback_failure_contract.json').read_bytes()
data=json.loads(out.read_bytes())
for path,digest in data['source_sha256'].items():
 source=subprocess.check_output(['git','show',PIN_FULL + ':'+path],cwd=root)
 assert hashlib.sha256(source).hexdigest()==digest,path
assert len(data['results'])==6
for row in data['results']:
 assert row['persisted'] and row['error']=='statement_invalid'
 assert row['calendar_jobs']==[] and row['announcements']==0
 assert len(row['invited'])==row['position']
print(f'WS11 merge Calendar Rails probe: 6 rejected-recipient/Meet cases regenerated byte-identical; 2 model sources matched {PIN}; 0 later Calendar callbacks enqueued jobs')
