#!/usr/bin/env python3
"""Verify renderer URL defaults, with and without the configured Rails APP_URL."""

from pin_identity import PIN, PIN_FULL, PIN_IMAGE
from pathlib import Path
import os
import subprocess

root = Path(__file__).resolve().parents[3]
env = dict(os.environ, PARITY_NAMESPACE='ws11', PARITY_OWNER='ws11',
           PARITY_IMAGE=PIN_IMAGE)
for name, origin, vector in [
    ('default', None, 'agents_stream_frames_contract.json'),
    ('configured', 'https://campfire.example.test:8443', 'agents_stream_configured_frames_contract.json'),
]:
    command = ['rust/parity/bin/reference', 'runner', '--seed', 'default', '-e', 'RAILS_LOG_LEVEL=fatal']
    if origin:
        command += ['-e', f'APP_URL={origin}']
    command += ['rust/reference-tools/agents/stream_frames_contract.rb']
    output = root / f'.scratch/stream-{name}-origin-verified.json'
    with output.open('wb') as stdout, (root / f'.scratch/stream-{name}-origin-verified.log').open('wb') as stderr:
        subprocess.run(command, cwd=root, env=env, stdout=stdout, stderr=stderr, check=True)
    assert output.read_bytes() == (root / f'rust/vectors/{vector}').read_bytes(), name
print(f'WS11 stream frame origins: default and configured start/update/final frames regenerated byte-identical ({PIN})')
