#!/usr/bin/env python3
"""Re-run the real Rails deletion/commit/poll interleavings without accepting drift."""
from pathlib import Path
import json
import os
import subprocess

root = Path(__file__).resolve().parents[3]
output = root / '.scratch/deletion-publication-verified.json'
env = dict(os.environ, PARITY_NAMESPACE='ws11', PARITY_OWNER='ws11',
           PARITY_IMAGE='triage-reference-d7c7de92')
with output.open('wb') as stdout, (root / '.scratch/deletion-publication-verified.log').open('wb') as stderr:
    subprocess.run(['rust/parity/bin/reference', 'runner', '--seed', 'default',
                    '-e', 'RAILS_LOG_LEVEL=fatal',
                    'rust/reference-tools/agents/deletion_publication_contract.rb'],
                   cwd=root, env=env, stdout=stdout, stderr=stderr, check=True)
assert output.read_bytes() == (root / 'rust/vectors/agents_deletion_publication_contract.json').read_bytes()
for name, result in json.loads(output.read_bytes())['results'].items():
    assert result['resumed_types'] == ['work_unassigned'], name
    assert result['resumed_cursor_is_deletion'] and result['deletion_count'] == 1, name
print('WS11 deletion publication Rails probes: 2 real commit/poll interleavings regenerated byte-identical (d7c7de92)')
