#!/usr/bin/env python3
"""Regenerate PR #176 probes against the pinned Rails image, without accepting drift."""

from pin_identity import PIN, PIN_FULL, PIN_IMAGE
import os,subprocess,json
from pathlib import Path
root=Path(__file__).resolve().parents[3]
output=root/'.scratch/review-fixes-verified.json'
log=root/'.scratch/review-fixes-verified.log'
env=dict(os.environ,PARITY_NAMESPACE='ws11',PARITY_OWNER='ws11',PARITY_IMAGE=PIN_IMAGE)
with output.open('wb') as out,log.open('wb') as err:
 subprocess.run(['rust/parity/bin/reference','runner','--seed','default','-e','RAILS_LOG_LEVEL=fatal','rust/reference-tools/agents/review_fixes_contract.rb'],cwd=root,env=env,stdout=out,stderr=err,check=True)
assert output.read_bytes()==(root/'rust/vectors/agents_review_fixes_contract.json').read_bytes()
v=json.loads(output.read_bytes())['results']
assert len(v['repositories'])==21
assert v['deletion']['thread_exists'] is False and v['deletion_with_webhook']['thread_exists'] is False
assert v['deletion_removed_agent']==dict(error=None,thread_exists=False,agent_exists=False,events=1)
assert v['stream_failure']['quote_references']==0 and v['approval']['notified_users']==[712064548]
print(f'WS11 review Rails probes: 21 repository batches, repeated-thread polling, deletion with/without webhook and captured-agent removal, real reference order and partial fanout regenerated byte-identical ({PIN})')
