#!/usr/bin/env python3
"""Regenerate the deletion failure's real Rails Turbo frames, without replacing callbacks."""
from pathlib import Path
import hashlib
import json
import os
import subprocess

root = Path(__file__).resolve().parents[3]
env = dict(os.environ, PARITY_NAMESPACE='ws11', PARITY_OWNER='ws11',
           PARITY_IMAGE='triage-reference-d7c7de92')
sources = ['app/models/channel_thread.rb', 'app/models/message.rb', 'app/models/agent.rb',
           'app/models/agent_approval.rb', 'app/models/user.rb', 'app/models/user/bot.rb',
           'app/services/agents/steps.rb', 'app/services/agents/direct_messages.rb',
           'app/views/messages/_thread_indicator.html.erb']
hashes = subprocess.check_output(['docker', 'run', '--rm', '--entrypoint', 'sha256sum',
                                 env['PARITY_IMAGE'], *['/rails/' + path for path in sources]],
                                cwd=root, text=True).splitlines()
for path, actual in zip(sources, hashes, strict=True):
    pinned = subprocess.check_output(['git', 'show', 'd7c7de92:' + path], cwd=root)
    assert actual.split()[0] == hashlib.sha256(pinned).hexdigest(), path
print(f'WS11 r5 Rails audit sources: {len(sources)}/{len(sources)} image files match d7c7de92')
out = root / '.scratch/r5-verified-indicator.json'
with out.open('wb') as stdout, (root / '.scratch/r5-verified-indicator.log').open('wb') as stderr:
    subprocess.run(['rust/parity/bin/reference', 'runner', '--seed', 'default', '-e',
                    'RAILS_LOG_LEVEL=fatal', 'rust/reference-tools/agents/deletion_indicator_contract.rb'],
                   cwd=root, env=env, stdout=stdout, stderr=stderr, check=True)
assert out.read_bytes() == (root / 'rust/vectors/agents_deletion_indicator_contract.json').read_bytes()
for result in json.loads(out.read_bytes())['results'].values():
    assert len(result['indicator_frames']) == 1
    assert result['thread_exists'] is False
    assert result['parent_exists'] is True
    assert result['replies_remaining'] == 0
print('WS11 r5 Rails deletion indicator: 4 webhook/failure cases regenerated byte-identical (d7c7de92); 1 indicator frame per case')
