#!/usr/bin/env bash
# Generate or verify the pinned Rails oracle for pending WS11 input seams.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
STORE=${STORE:-../.scratch/bot-input-contract}
mkdir -p "$STORE"
WORK=$(mktemp -d -p "$STORE" run.XXXXXX)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/db" "$WORK/storage"
docker run --rm --name "${PARITY_OWNER:-ws11ui}-bot-input-contract" --cpus 2 \
  --user "$(id -u):$(id -g)" --env-file parity/.env.reference \
  -e RAILS_LOG_LEVEL=warn -e PARITY_REDIS=1 -e 'FAKETIME=2026-02-10 12:00:00' \
  -v "$(realpath "$WORK/db"):/rails/storage/db" -v "$(realpath "$WORK/storage"):/rails/storage/files" \
  -v "$ROOT:/work:ro" "${PARITY_IMAGE:-ws11ui-reference:d7c7de92}" \
  bash -c 'bin/rails db:prepare >/dev/null && bin/rails runner /work/reference-tools/views/bots_ui/input_contract.rb'
if [ "${1:-}" = --check ]; then
  cmp "$WORK/db/bot-input-contract.json" vectors/bot-input-contract.json
  echo 'Rails bot input contract: committed corpus matches regenerated bytes'
else
  cp "$WORK/db/bot-input-contract.json" vectors/bot-input-contract.json
fi
