#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
STORE=${STORE:-../.scratch/bots-ui-reference}
mkdir -p "$STORE"
WORK=$(mktemp -d -p "$STORE" run.XXXXXX)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/db" "$WORK/storage"
# The shared wave rules explicitly move this layout oracle to the status-popup fix.
# All other Rails code and assets remain in the pinned d7c7de92 image.
git -C "$ROOT/.." show '2e20b24c3f2be9db8a646a1352c159b4afacad0e:app/views/layouts/application.html.erb' > "$WORK/application.html.erb"
docker run --rm --name "${PARITY_OWNER:-ws11ui}-bots-ui-goldens" --cpus 2 \
  --user "$(id -u):$(id -g)" --env-file parity/.env.reference \
  -e RAILS_LOG_LEVEL=warn -e PARITY_REDIS=1 -e 'FAKETIME=2026-02-10 12:00:00' \
  -v "$(realpath "$WORK/db"):/rails/storage/db" -v "$(realpath "$WORK/storage"):/rails/storage/files" \
  -v "$(realpath "$WORK/application.html.erb"):/rails/app/views/layouts/application.html.erb:ro" \
  -v "$ROOT:/work:ro" "${PARITY_IMAGE:-ws11ui-reference:d7c7de92}" \
  bash -c 'bin/rails db:prepare >/dev/null && bin/rails runner /work/reference-tools/views/bots_ui/goldens.rb'
mkdir -p crates/views/tests/golden/bots_ui
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/db/bots-ui.json" crates/views/tests/golden/bots_ui/pages.json
  echo "bots-ui: committed page corpus matches regenerated bytes"
else
  cp "$WORK/db/bots-ui.json" crates/views/tests/golden/bots_ui/pages.json
fi
