//! HTTP security regressions against d336ca78; expectations generated by pinned Rails.
use crate::controllers::presenters::test_support::{Browser, DAVID, KEVIN, Req, TestApp};
use axum::http::{Method, StatusCode};
use campfire_db::{TwoFactorRememberedDevice, User};
use serde_json::{Value, json};
use std::sync::Arc;

const CHROME: &str = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
fn vectors() -> Value {
    serde_json::from_str(include_str!(
        "../../../../vectors/round_three_security.json"
    ))
    .unwrap()
}
async fn app() -> TestApp {
    TestApp::boot_with_clock(Arc::new(campfire_kit::FrozenClock::new(
        crate::controllers::presenters::test_support::SEED_NOW
            .parse()
            .unwrap(),
    )))
    .await
    .expect("build the pinned WS19 default seed")
}
fn request(method: Method, path: &str) -> Req {
    Req::new(method, path)
        .header("user-agent", CHROME)
        .header("x-forwarded-for", "127.0.0.1")
}
fn json_request(method: Method, path: &str, value: &Value) -> Req {
    request(method, path)
        .header("content-type", "application/json")
        .body(value.to_string())
}
async fn audits(a: &TestApp) -> Value {
    a.db()
        .read(|c| {
            let ids = c
                .prepare("SELECT id FROM audit_logs ORDER BY id")?
                .query_map([], |r| r.get::<_, i64>(0))?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            Ok(Value::Array(
                ids.into_iter()
                    .map(|id| {
                        campfire_db::models::audit_log::AuditLog::find(c, id)
                            .map(|row| row.snapshot())
                    })
                    .collect::<campfire_db::Result<Vec<_>>>()?,
            ))
        })
        .await
        .unwrap()
}
async fn clear_audits(a: &TestApp) {
    a.db()
        .write(|tx| {
            tx.conn().execute("DELETE FROM audit_logs", [])?;
            Ok(())
        })
        .await
        .unwrap();
}
async fn password_case(name: &str) {
    let case = &vectors()["password"][name];
    let a = app().await;
    clear_audits(&a).await;
    a.db()
        .write(|tx| {
            TwoFactorRememberedDevice::revoke_all(tx, DAVID)?;
            TwoFactorRememberedDevice::create_for(tx, DAVID, Some(CHROME), Some("127.0.0.1"))?;
            Ok(())
        })
        .await
        .unwrap();
    let before = a.db().read(|c| User::find(c, DAVID)).await.unwrap();
    let mut b = a.sign_in(DAVID).await;
    b.get("/users/me/profile").await;
    let response = b
        .write(json_request(
            Method::PATCH,
            "/users/me/profile",
            &json!({"user":{"password":case["value"]}}),
        ))
        .await;
    assert_eq!(json!(response.status.as_u16()), case["status"], "{name}");
    let saved = a.db().read(|c| User::find(c, DAVID)).await.unwrap();
    assert_eq!(
        json!(before.password_digest != saved.password_digest),
        case["changed"],
        "{name}"
    );
    let devices = a
        .db()
        .read(|c| TwoFactorRememberedDevice::for_user(c, DAVID))
        .await
        .unwrap();
    assert_eq!(
        json!(devices.len()),
        case["devices"],
        "{name}: raw password presence must revoke devices even when strong parameters discard it"
    );
    assert_eq!(audits(&a).await, case["audits"], "{name}");
}
#[tokio::test]
async fn array_password_uses_raw_presence_for_device_revocation_and_audit() {
    password_case("array").await;
    password_case("empty_array").await;
    password_case("nil").await;
}
#[tokio::test]
async fn object_password_uses_raw_presence_for_device_revocation_and_audit() {
    password_case("hash").await;
    password_case("empty_hash").await;
}
#[tokio::test]
async fn failed_sign_in_audits_ruby_array_string_before_filtering() {
    for name in ["array", "two", "escaped", "empty_array", "nil"] {
        let case = &vectors()["email"][name];
        let a = app().await;
        clear_audits(&a).await;
        let mut b = a.anonymous();
        b.get("/session/new").await;
        let response = b
            .write(json_request(
                Method::POST,
                "/session",
                &json!({"email_address":case["value"],"password":"wrong"}),
            ))
            .await;
        assert_eq!(json!(response.status.as_u16()), case["status"], "{name}");
        assert_eq!(audits(&a).await, case["audits"], "{name}");
    }
}
#[tokio::test]
async fn rate_limited_sign_in_audits_ruby_array_string_before_filtering() {
    let case = &vectors()["rate"];
    let a = app().await;
    clear_audits(&a).await;
    let mut b = a.anonymous();
    b.get("/session/new").await;
    for _ in 0..10 {
        assert_eq!(
            b.write(request(Method::POST, "/session").form(&[
                ("email_address", "david@37signals.com"),
                ("password", "wrong")
            ]))
            .await
            .status,
            StatusCode::UNAUTHORIZED
        );
    }
    let response = b
        .write(json_request(
            Method::POST,
            "/session",
            &json!({"email_address":case["value"],"password":"wrong"}),
        ))
        .await;
    assert_eq!(json!(response.status.as_u16()), case["status"]);
    assert_eq!(audits(&a).await, case["audits"]);
}
#[tokio::test]
async fn submitted_time_zone_marks_choice_only_after_successful_save() {
    for name in [
        "blank",
        "whitespace",
        "selected",
        "alias",
        "nil",
        "array",
        "hash",
        "absent",
        "rejected",
        "invalid",
        "already_explicit",
    ] {
        let case = &vectors()["zone"][name];
        let a = app().await;
        clear_audits(&a).await;
        let explicit = name == "already_explicit";
        a.db()
            .write(move |tx| {
                tx.conn().execute(
                    "UPDATE users SET time_zone='UTC',time_zone_explicit=? WHERE id=?",
                    rusqlite::params![explicit, DAVID],
                )?;
                Ok(())
            })
            .await
            .unwrap();
        let mut b = a.sign_in(DAVID).await;
        let before = a.db().read(|c| User::find(c, DAVID)).await.unwrap();
        b.get("/users/me/profile").await;
        let response = b
            .write(json_request(
                Method::PATCH,
                "/users/me/profile",
                &json!({"user":case["params"]}),
            ))
            .await;
        assert_eq!(json!(response.status.as_u16()), case["status"], "{name}");
        let (zone, explicit): (Option<String>, bool) = a
            .db()
            .read(|c| {
                Ok(c.query_row(
                    "SELECT time_zone,time_zone_explicit FROM users WHERE id=?",
                    [DAVID],
                    |r| Ok((r.get(0)?, r.get(1)?)),
                )?)
            })
            .await
            .unwrap();
        assert_eq!(
            json!(explicit),
            case["explicit"],
            "{name}: Rails marks any raw time_zone key, including Not set, nil and filtered values"
        );
        assert_eq!(json!(zone), case["zone"], "{name}");
        assert_eq!(audits(&a).await, case["audits"], "{name}");
        if case["status"] == 422 {
            assert_eq!(
                a.db().read(|c| User::find(c, DAVID)).await.unwrap(),
                before,
                "{name}: a failed save must not persist any submitted profile change or marker"
            );
        }
    }
}
async fn admin_browser(a: &TestApp) -> Browser<'_> {
    let mut b = a.sign_in(DAVID).await;
    b.get("/users/me/profile").await;
    assert_eq!(
        b.write(request(Method::POST, "/sudo").form(&[("password", "secret123456")]))
            .await
            .status,
        StatusCode::FOUND
    );
    clear_audits(a).await;
    b
}
async fn prepare_target(a: &TestApp, case: &Value) {
    let role = campfire_db::Role::from_name(case["before_role"].as_str().unwrap()).unwrap();
    let status = campfire_db::Status::from_name(case["before_status"].as_str().unwrap()).unwrap();
    a.db()
        .write(move |tx| {
            tx.conn().execute(
                "UPDATE users SET role=?,status=? WHERE id=?",
                rusqlite::params![role, status, KEVIN],
            )?;
            tx.conn().execute(
                "UPDATE sessions SET ip_address='203.0.113.9' WHERE user_id=?",
                [KEVIN],
            )?;
            Ok(())
        })
        .await
        .unwrap();
}
fn admin_request(case: &Value) -> Req {
    let method =
        Method::from_bytes(case["method"].as_str().unwrap().to_uppercase().as_bytes()).unwrap();
    let path = if case["route"] == "account" {
        format!("/account/users/{KEVIN}")
    } else {
        format!("/users/{KEVIN}/ban")
    };
    json_request(method, &path, &case["params"])
}
async fn admin_case(name: &str) {
    let case = &vectors()["admin"][name];
    let a = app().await;
    prepare_target(&a, case).await;
    let before = a.db().read(|c| User::find(c, KEVIN)).await.unwrap();
    let mut b = admin_browser(&a).await;
    let response = b.write(admin_request(case)).await;
    assert_eq!(
        json!(response.status.as_u16()),
        case["status"],
        "{name}: {}",
        response.text()
    );
    assert_eq!(
        audits(&a).await,
        case["audits"],
        "{name}: exact actor/target labels, details, IP and UA"
    );
    let saved = a.db().read(|c| User::find(c, KEVIN)).await.unwrap();
    assert_eq!(json!(saved.status.name()), case["user_status"], "{name}");
    assert_eq!(json!(saved.role.name()), case["user_role"], "{name}");
    if name == "deactivate" {
        assert_ne!(saved.email_address, before.email_address);
        assert_eq!(
            case["audits"][0]["target_label"],
            json!(campfire_db::models::audit_log::Actor::from(&before).label)
        );
    }
}
#[tokio::test]
async fn role_audits_match_successful_transitions_and_ignore_noops() {
    for name in ["promote", "demote", "role_noop", "invalid_role"] {
        admin_case(name).await;
    }
}
#[tokio::test]
async fn deactivation_audit_keeps_target_label_before_email_rewrite() {
    admin_case("deactivate").await;
}
#[tokio::test]
async fn ban_audits_match_transitions_including_deactivated_users_and_noops() {
    for name in ["ban", "ban_noop", "ban_deactivated"] {
        admin_case(name).await;
    }
}
#[tokio::test]
async fn unban_audits_match_transitions_including_deactivated_users_and_noops() {
    for name in ["unban", "unban_noop", "unban_deactivated"] {
        admin_case(name).await;
    }
}
#[tokio::test]
async fn admin_audit_failure_rolls_back_role_deactivation_and_ban_mutations() {
    for name in ["promote", "deactivate", "ban", "unban"] {
        let case = &vectors()["admin"][name];
        let a = app().await;
        prepare_target(&a, case).await;
        let mut b = admin_browser(&a).await;
        let before = a.db().read(|c| User::find(c, KEVIN)).await.unwrap();
        let snapshot = |c: &campfire_db::Connection| -> campfire_db::Result<Vec<i64>> {
            ["sessions", "memberships", "bans", "user_devices"]
                .iter()
                .map(|table| {
                    Ok(c.query_row(
                        &format!("SELECT count(*) FROM {table} WHERE user_id=?"),
                        [KEVIN],
                        |r| r.get(0),
                    )?)
                })
                .collect()
        };
        let related = a.db().read(snapshot).await.unwrap();
        a.db().write(|tx| {
            tx.conn().execute_batch("CREATE TRIGGER reject_admin_audit BEFORE INSERT ON audit_logs BEGIN SELECT RAISE(ABORT,'review audit failure'); END;")?;
            Ok(())
        }).await.unwrap();
        let response = b.write(admin_request(case)).await;
        assert_eq!(response.status, StatusCode::INTERNAL_SERVER_ERROR, "{name}");
        assert_eq!(
            a.db().read(|c| User::find(c, KEVIN)).await.unwrap(),
            before,
            "{name}"
        );
        assert_eq!(a.db().read(snapshot).await.unwrap(), related, "{name}");
        assert_eq!(audits(&a).await, json!([]), "{name}");
    }
}
