//! Aggregate-only validators from MessagesController#rendered_{related,pin}_stamp.
use campfire_db::{Connection, Message, Result, Timestamp};
use sha2::{Digest, Sha256};

use crate::controllers::presenters::cache_key_with_version;

pub fn etag(conn: &Connection, messages: &[Message]) -> Result<String> {
    let ids = messages.iter().map(|message| message.id).collect::<Vec<_>>();
    let placeholders = std::iter::repeat_n("?", ids.len()).collect::<Vec<_>>().join(",");
    // Only timestamps/ids are selected. No rich-text, blob, card or creator records are loaded
    // until fresh_when has established that the browser's page needs rendering.
    let sql = format!(r#"
        WITH page AS (SELECT id, creator_id, reply_to_message_id, edited_at FROM messages WHERE id IN ({placeholders}))
        SELECT MAX(stamp) FROM (
          SELECT MAX(edited_at) AS stamp FROM page
          UNION ALL SELECT MAX(updated_at) FROM messages WHERE id IN (SELECT reply_to_message_id FROM page)
          UNION ALL SELECT MAX(edited_at) FROM messages WHERE id IN (SELECT reply_to_message_id FROM page)
          UNION ALL SELECT MAX(c.updated_at) FROM github_pull_request_references r JOIN github_pull_requests c ON c.id = r.github_pull_request_id WHERE r.message_id IN (SELECT id FROM page)
          UNION ALL SELECT MAX(c.updated_at) FROM twitter_post_references r JOIN twitter_posts c ON c.id = r.twitter_post_id WHERE r.message_id IN (SELECT id FROM page)
          UNION ALL SELECT MAX(c.updated_at) FROM link_embed_references r JOIN link_embeds c ON c.id = r.link_embed_id WHERE r.message_id IN (SELECT id FROM page)
          UNION ALL SELECT MAX(c.updated_at) FROM event_references r JOIN events c ON c.id = r.event_id WHERE r.message_id IN (SELECT id FROM page)
          UNION ALL SELECT MAX(updated_at) FROM polls WHERE message_id IN (SELECT id FROM page)
          UNION ALL SELECT MAX(updated_at) FROM messages WHERE id IN (SELECT referenced_message_id FROM message_references WHERE message_id IN (SELECT id FROM page))
          UNION ALL SELECT MAX(edited_at) FROM messages WHERE id IN (SELECT referenced_message_id FROM message_references WHERE message_id IN (SELECT id FROM page))
          UNION ALL SELECT MAX(updated_at) FROM users WHERE id IN (SELECT creator_id FROM page)
        )"#);
    let related: Option<Timestamp> = conn.query_row(&sql, rusqlite::params_from_iter(&ids), |row| row.get(0))?;
    let pairs = conn.prepare(&format!("SELECT message_id, id FROM message_pins WHERE message_id IN ({placeholders}) ORDER BY message_id, id"))?
        .query_map(rusqlite::params_from_iter(&ids), |row| Ok(format!("[{}, {}]", row.get::<_, i64>(0)?, row.get::<_, i64>(1)?)))?
        .collect::<std::result::Result<Vec<_>, _>>()?;
    let pin_stamp = format!("{:x}", Sha256::digest(format!("[{}]", pairs.join(", "))));
    let record_keys = messages.iter().map(|message| cache_key_with_version("messages", message.id, message.updated_at.jiff())).collect::<Vec<_>>().join("/");
    let related_stamp = related.map(|time| time.jiff().strftime("%Y%m%d%H%M%S%6f").to_string()).unwrap_or_default();
    Ok(format!("{record_keys}/{related_stamp}/{pin_stamp}/{}", campfire_views::fragment_cache::keys::PRESENTATION_CACHE_VERSION))
}

/// ActionView::Digestor's pinned Rails digest, regenerated by reference-tools/messaging/paging.rb.
pub const INDEX_TEMPLATE_DIGEST: &str = "8c84e9c3391ab09f136a472ad8ab8b69";

#[cfg(test)]
mod tests {
    #[test]
    fn index_template_digest_matches_rails_vector() {
        assert_eq!(
            super::INDEX_TEMPLATE_DIGEST,
            include_str!("../../../../../vectors/messaging/index-template-digest.txt").trim()
        );
    }
}
