#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" bot-boundaries.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze \
  reference-tools/views/agents_ui/bot_boundaries.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/bot-ui-mutation-boundaries.json
  echo 'Rails bot mutation boundaries: committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/bot-ui-mutation-boundaries.json
fi
