#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" render-replay.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/casting_followups.rb > "$WORK/oracle.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/oracle.json" vectors/bot-ui-casting-followups.json
else
  cp "$WORK/oracle.json" vectors/bot-ui-casting-followups.json
fi
echo 'Rails casting follow-up oracle regenerated byte-identically'
