#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" concurrent-edits.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/concurrent_edits.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
 cmp "$WORK/corpus.json" vectors/bot-ui-concurrent-edits.json
 echo 'Rails concurrent edits: committed corpus matches regenerated bytes'
else
 cp "$WORK/corpus.json" vectors/bot-ui-concurrent-edits.json
fi
