#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
STORE=${STORE:-../.scratch/agents-ui-downcase}
mkdir -p "$STORE"
WORK=$(mktemp -d -p "$STORE" run.XXXXXX)
trap 'rm -rf "$WORK"' EXIT
PIN=$(cat parity/reference.sha)
docker run --rm --name "${PARITY_OWNER:-ws11ui}-downcase" --cpus 2 \
  --entrypoint ruby -v "$ROOT:/work:ro" "${PARITY_IMAGE:-ws11ui-reference:d7c7de92}" \
  /work/reference-tools/views/agents_ui/downcase.rb "$PIN" > "$WORK/mappings.json"
python3 - "$WORK/mappings.json" "$WORK/downcase.rs" "$PIN" <<'PY'
import json
from pathlib import Path
import sys
mappings = json.loads(Path(sys.argv[1]).read_text())
lines = [f'// Generated by reference-tools/views/agents_ui/downcase.sh from Rails {sys.argv[3]}.',
         '// Ruby downcases individual characters without contextual final-sigma substitution.',
         'pub(super) const MAPPINGS: &[(char, &str)] = &[']
lines += [f'    (\'\\u{{{codepoint:x}}}\', {json.dumps(lower, ensure_ascii=False)}),' for codepoint, lower in mappings]
lines += ['];', '']
Path(sys.argv[2]).write_text('\n'.join(lines))
print(f'Rails downcase table: {len(mappings)} changed Unicode scalars')
PY
mkdir -p crates/db/src/models/agent_profile
DEST=crates/db/src/models/agent_profile/downcase_table.rs
if [ "${1:-}" = --check ]; then
  cmp "$WORK/downcase.rs" "$DEST"
  echo 'Rails downcase table: committed bytes match reference'
else
  cp "$WORK/downcase.rs" "$DEST"
fi
