#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" extreme-casts.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
for name in extreme_casts extreme_http_boundaries generated_extreme_casts; do
  case "$name" in
    extreme_casts) vector=bot-ui-extreme-casts;;
    extreme_http_boundaries) vector=bot-ui-extreme-http;;
    generated_extreme_casts) vector=bot-ui-generated-extremes;;
  esac
  bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze "reference-tools/views/agents_ui/$name.rb" > "$WORK/$vector.json"
  if [[ "${1:-}" == --check ]]; then
    cmp "$WORK/$vector.json" "vectors/$vector.json"
  else
    cp "$WORK/$vector.json" "vectors/$vector.json"
  fi
done
echo 'Rails extreme cast corpora: 11256 model dates, 2189 raw tokens, 56 HTTP expiry cases and 17 HTTP tokens, 3240 further dates and 208 further raw tokens match regenerated bytes'
