#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" inbox-http.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze \
  reference-tools/views/agents_ui/inbox_http.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/inbox-http.json
  echo 'inbox Rails HTTP fixtures: committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/inbox-http.json
fi
