#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" inbox-lifecycle.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/inbox_lifecycle.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-inbox-lifecycle.json
  echo 'Rails inbox lifecycle: reminder, recurrence and deleted-source; committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/agent-inbox-lifecycle.json
fi
