#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" page-reads.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-09-23T16:00:00Z --freeze reference-tools/views/agents_ui/named_broadcasts.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-named-ui-broadcasts.json
  echo 'Rails named UI broadcast oracle regenerated byte-identically'
else
  cp "$WORK/corpus.json" vectors/agent-named-ui-broadcasts.json
fi
