#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" page-reads.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
PARITY_IMAGE=${PARITY_IMAGE:-campfire-reference} bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/navigation_matrix.rb > "$WORK/corpus.json"
python3 -m json.tool "$WORK/corpus.json" > /dev/null
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-navigation-matrix.json
  echo 'Rails navigation matrix regenerated byte-identically'
else
  cp "$WORK/corpus.json" vectors/agent-navigation-matrix.json
fi
