#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" normalized-casts.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
for name in normalized_casts normalized_tokens_http boundary_expiry_http json_exponent_boundaries; do
  case "$name" in
    normalized_casts) vector=bot-ui-normalized-casts;;
    normalized_tokens_http) vector=bot-ui-normalized-tokens-http;;
    json_exponent_boundaries) vector=bot-ui-json-exponent-boundaries;;
    boundary_expiry_http) vector=bot-ui-boundary-expiry-http;;
  esac
  bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze "reference-tools/views/agents_ui/$name.rb" > "$WORK/$vector.json"
  if [[ "${1:-}" == --check ]]; then
    cmp "$WORK/$vector.json" "vectors/$vector.json"
  else
    cp "$WORK/$vector.json" "vectors/$vector.json"
  fi
done
echo 'Rails normalized corpora: 19360 dates, 461 raw tokens, 29 token HTTP cases 8 credential save/read cases and 312 further exponent tokens match regenerated bytes'
