#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" numeric-expiry.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/numeric_expiry.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-numeric-expiry.json
  echo 'Rails raw credential expiry: 10 HTTP saves and model reads; committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/agent-numeric-expiry.json
fi
