#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" page-read-boundaries.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/page_read_boundaries.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-page-read-boundaries.json
  echo 'Rails page-read boundaries: committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/agent-page-read-boundaries.json
fi
