#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" page-reads.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/page_reads.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-page-reads.json
  echo 'Rails page-read oracle: committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/agent-page-reads.json
fi
