#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
cd "$ROOT"
WORK=$(mktemp -d -p "${TMPDIR:-../.scratch}" tour-values.XXXXXX)
trap 'rm -rf -- "$WORK"' EXIT
bash parity/bin/reference runner --seed default --time 2026-03-02T16:00:00Z --freeze reference-tools/views/agents_ui/tour_values.rb > "$WORK/corpus.json"
if [[ "${1:-}" == --check ]]; then
  cmp "$WORK/corpus.json" vectors/agent-tour-values.json
  echo 'Rails tour datetime corpus: 194 values, 388 raw fragments; committed corpus matches regenerated bytes'
else
  cp "$WORK/corpus.json" vectors/agent-tour-values.json
fi
