//! Astra round-2 probes, with expectations regenerated by ws8_round2_vectors.rb.
use super::room_delete_test::{assert_checks, setup};
use super::*;
use crate::broadcasts::{Broadcast, Partial};
use crate::models::room_delete::HuddleConfig;
use crate::models::{retention, room_delete};
use crate::rich_text::UserNames;
use crate::{Message, MessageChanges, NewMessage, RichText, Room};
use serde_json::{Value, json};
use std::sync::atomic::{AtomicUsize, Ordering};

fn golden() -> Value {
    serde_json::from_str(include_str!("ws8_round2_vectors.json")).unwrap()
}

#[test]
fn synchronous_room_destroy_matches_rails_dependencies() {
    let g = golden()["synchronous"].clone();
    let t = setup(&g);
    let rid = g["room_id"].as_i64().unwrap();
    t.write(move |tx| Room::find(tx.conn(), rid)?.destroy(tx));
    assert_checks(&t, &g["checks"]);
}

#[test]
fn asynchronous_room_destroy_matches_rails_preliminary_deletions() {
    let g = golden()["asynchronous"].clone();
    let t = setup(&g);
    let rid = g["room_id"].as_i64().unwrap();
    t.write(move |tx| {
        room_delete::begin_destroy(tx, &Room::find(tx.conn(), rid)?, &HuddleConfig::default())
    });
    tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(room_delete::perform_with_config(
            &t.db,
            rid,
            HuddleConfig::default(),
        ))
        .unwrap();
    assert_checks(&t, &g["checks"]);
}

#[test]
fn room_501_messages_resume_matches_rails_progress() {
    let g = golden()["room_resume"].clone();
    let t = setup(&g);
    let rid = g["room_id"].as_i64().unwrap();
    let index = g["setup_index_sql"].as_str().unwrap().to_owned();
    t.write(move |tx| {
        tx.conn().execute_batch(&index)?;
        tx.conn().execute_batch("CREATE TRIGGER reviewer_stop BEFORE DELETE ON messages WHEN OLD.id=2000000501 BEGIN SELECT RAISE(ABORT,'interruption'); END")?;
        room_delete::begin_destroy(tx, &Room::find(tx.conn(), rid)?, &HuddleConfig::default())
    });
    let rt = tokio::runtime::Runtime::new().unwrap();
    assert!(
        rt.block_on(room_delete::perform_with_config(
            &t.db,
            rid,
            HuddleConfig::default()
        ))
        .is_err()
    );
    assert_checks(&t, &g["progress"]);
    t.write(|tx| {
        tx.conn().execute_batch("DROP TRIGGER reviewer_stop")?;
        Ok(())
    });
    rt.block_on(room_delete::perform_with_config(
        &t.db,
        rid,
        HuddleConfig::default(),
    ))
    .unwrap();
    assert_checks(&t, &g["finished"]);
}

#[test]
fn retention_1001_grants_resume_matches_rails_progress() {
    let g = golden()["retention_resume"].clone();
    let t = setup(&g);
    t.write(|tx| {
        tx.conn().execute_batch("CREATE TRIGGER reviewer_stop BEFORE DELETE ON huddle_grants WHEN OLD.id=2000001001 BEGIN SELECT RAISE(ABORT,'interruption'); END")?;
        Ok(())
    });
    let rt = tokio::runtime::Runtime::new().unwrap();
    assert!(rt.block_on(retention::perform(&t.db)).is_err());
    assert_checks(&t, &g["progress"]);
    t.write(|tx| {
        tx.conn().execute_batch("DROP TRIGGER reviewer_stop")?;
        Ok(())
    });
    rt.block_on(retention::perform(&t.db)).unwrap();
    assert_checks(&t, &g["finished"]);
}

struct TransientRenderer(AtomicUsize);
impl RichText for TransientRenderer {
    fn to_plain_text(&self, c: &Connection, s: &str, n: UserNames<'_>) -> String {
        BasicRichText.to_plain_text(c, s, n)
    }
    fn mentioned_user_ids(&self, c: &Connection, s: &str) -> Vec<i64> {
        BasicRichText.mentioned_user_ids(c, s)
    }
    fn try_to_plain_text(
        &self,
        c: &Connection,
        s: &str,
        n: UserNames<'_>,
    ) -> std::result::Result<String, String> {
        if self.0.fetch_add(1, Ordering::SeqCst) == 1 {
            Err("post-preflight renderer failure".into())
        } else {
            Ok(self.to_plain_text(c, s, n))
        }
    }
}

#[test]
fn renderer_failure_after_preflight_rolls_back_message() {
    let t = TestDb::new();
    let mut config = Config::new(t.db.path());
    config.prepare = false;
    let db = Database::open(
        config,
        Env {
            rich_text: Arc::new(TransientRenderer(AtomicUsize::new(0))),
            ..t.db.env().clone()
        },
    )
    .unwrap();
    let room = t.read(|c| Room::find(c, id("designers")));
    let result = db.write_blocking(|tx| {
        Message::create(
            tx,
            NewMessage {
                room_id: id("designers"),
                creator_id: id("david"),
                body: Some("<p>review</p>".into()),
                client_message_id: Some("review-transient".into()),
                ..Default::default()
            },
        )
    });
    assert!(result.is_err());
    let persisted = t.read(|c| {
        Ok(c.query_row::<i64, _, _>(
            "SELECT COUNT(*) FROM messages WHERE client_message_id='review-transient'",
            [],
            |r| r.get(0),
        )?)
    });
    assert_eq!(
        persisted, 0,
        "failed rendering must roll back the complete message write"
    );
    assert_eq!(t.read(|c| Room::find(c, id("designers"))), room);
    assert!(
        t.events().is_empty(),
        "a rolled-back write cannot broadcast or wake a job"
    );
}

#[test]
fn successful_bookkeeping_and_callback_order_match_rails() {
    let g = golden()["bookkeeping"].clone();
    let t = setup(&g);
    let rid = g["room_id"].as_i64().unwrap();
    let uid = g["creator_id"].as_i64().unwrap();
    let tid = g["thread_id"].as_i64().unwrap();
    let body = g["body"].as_str().unwrap().to_owned();
    let copy = body.clone();
    t.write(move |tx| {
        Message::create(
            tx,
            NewMessage {
                room_id: rid,
                creator_id: uid,
                body: Some(body),
                client_message_id: Some("review-root".into()),
                ..Default::default()
            },
        )
    });
    t.write(move |tx| {
        Message::create(
            tx,
            NewMessage {
                room_id: rid,
                creator_id: uid,
                thread_id: Some(tid),
                body: Some(copy),
                client_message_id: Some("review-thread".into()),
                ..Default::default()
            },
        )
    });
    assert_checks(&t, &g["checks"]);
    let events: Vec<Value> = t.events().into_iter().filter_map(|event| match event {
        Event::PushMessage { room_id, message_id } => Some(json!({"kind":"push", "class":"Room::PushMessageJob", "conversation_id":room_id, "message_id":message_id})),
        Event::Job(job) if job.class == "ChannelThread::PushMessageJob" => Some(json!({"kind":"push", "class":job.class, "conversation_id":job.arguments["thread_id"], "message_id":job.arguments["message_id"]})),
        Event::Broadcast(request) => {
            let broadcast = request.decode::<Broadcast>()?.unwrap();
            if let Some((stream, payload)) = broadcast.channel_frame() {
                return Some(json!({"kind":"cable", "stream":stream, "payload":payload}));
            }
            match broadcast {
                Broadcast::Turbo(stream) => match stream.partial {
                    Some(Partial::ThreadIndicator { message_id, reply_count }) => Some(json!({"kind":"indicator", "parent_message_id":message_id, "count":reply_count})),
                    _ => None,
                },
                _ => None,
            }
        }
        _ => None,
    }).collect();
    assert_eq!(json!(events), g["events"]);
}

fn bookkeeping_rows(conn: &Connection) -> Result<[i64; 4]> {
    Ok(conn.query_row(
        "SELECT (SELECT COUNT(*) FROM messages), (SELECT COUNT(*) FROM message_search_index), (SELECT COUNT(*) FROM action_text_rich_texts), (SELECT COUNT(*) FROM message_references)",
        [],
        |row| Ok([row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?]),
    )?)
}

fn bookkeeping_failure(trigger: &str) {
    let g = golden()["bookkeeping"].clone();
    let t = setup(&g);
    let rid = g["room_id"].as_i64().unwrap();
    let room = t.read(|c| Room::find(c, rid));
    let memberships = t.read(|c| crate::Membership::for_room(c, rid));
    let rows = t.read(bookkeeping_rows);
    let trigger = trigger.to_owned();
    t.write(move |tx| {
        tx.conn().execute_batch(&trigger)?;
        Ok(())
    });
    let body = g["body"].as_str().unwrap().to_owned();
    let uid = g["creator_id"].as_i64().unwrap();
    assert!(
        t.try_write(move |tx| Message::create(
            tx,
            NewMessage {
                room_id: rid,
                creator_id: uid,
                body: Some(body),
                client_message_id: Some("review-failure".into()),
                ..Default::default()
            }
        ))
        .is_err()
    );
    assert_eq!(t.read(bookkeeping_rows), rows);
    assert_eq!(t.read(|c| Room::find(c, rid)), room);
    assert_eq!(t.read(|c| crate::Membership::for_room(c, rid)), memberships);
    assert!(t.events().is_empty());
}

#[test]
fn unread_failure_rolls_back_message_and_index() {
    bookkeeping_failure(
        "CREATE TRIGGER reviewer_stop BEFORE UPDATE ON memberships BEGIN SELECT RAISE(ABORT,'unread bookkeeping failed'); END",
    );
}

#[test]
fn reference_failure_rolls_back_message_index_and_unread() {
    bookkeeping_failure(
        "CREATE TRIGGER reviewer_stop BEFORE INSERT ON message_references BEGIN SELECT RAISE(ABORT,'reference bookkeeping failed'); END",
    );
}

struct FailOnStoredBody;
impl RichText for FailOnStoredBody {
    fn to_plain_text(&self, c: &Connection, s: &str, n: UserNames<'_>) -> String {
        BasicRichText.to_plain_text(c, s, n)
    }
    fn mentioned_user_ids(&self, c: &Connection, s: &str) -> Vec<i64> {
        BasicRichText.mentioned_user_ids(c, s)
    }
    fn try_to_plain_text(
        &self,
        c: &Connection,
        s: &str,
        n: UserNames<'_>,
    ) -> std::result::Result<String, String> {
        let stored: bool = c.query_row("SELECT EXISTS(SELECT 1 FROM action_text_rich_texts WHERE body='<p>edited review</p>')", [], |r| r.get(0)).unwrap();
        if stored {
            Err("index renderer failed after edit".into())
        } else {
            Ok(self.to_plain_text(c, s, n))
        }
    }
}

#[test]
fn edit_index_failure_rolls_back_body_and_timestamps() {
    let t = TestDb::new();
    let before = t.read(|c| Message::find(c, id("first")));
    let body = t.read(|c| before.body_html(c));
    let mut config = Config::new(t.db.path());
    config.prepare = false;
    let db = Database::open(
        config,
        Env {
            rich_text: Arc::new(FailOnStoredBody),
            ..t.db.env().clone()
        },
    )
    .unwrap();
    t.travel(1);
    assert!(
        db.write_blocking(|tx| Message::find(tx.conn(), id("first"))?.edit(
            tx,
            MessageChanges {
                body: Some("<p>edited review</p>".into()),
                ..Default::default()
            }
        ))
        .is_err()
    );
    assert_eq!(t.read(|c| Message::find(c, id("first"))), before);
    assert_eq!(
        t.read(|c| Message::find(c, id("first"))?.body_html(c)),
        body
    );
    assert!(t.events().is_empty());
}

#[test]
fn touch_index_failure_rolls_back_timestamps() {
    let t = TestDb::new();
    let before = t.read(|c| Message::find(c, id("first")));
    let room = t.read(|c| before.room(c));
    let mut config = Config::new(t.db.path());
    config.prepare = false;
    let db = Database::open(
        config,
        Env {
            rich_text: Arc::new(TransientRenderer(AtomicUsize::new(1))),
            ..t.db.env().clone()
        },
    )
    .unwrap();
    t.travel(1);
    assert!(
        db.write_blocking(|tx| Message::find(tx.conn(), id("first"))?.touch(tx))
            .is_err()
    );
    assert_eq!(t.read(|c| Message::find(c, id("first"))), before);
    assert_eq!(t.read(|c| Room::find(c, id("designers"))), room);
    assert!(t.events().is_empty());
}
