#!/usr/bin/env python3
"""Verify regeneration of every observed Rails frame, handoff and banner state."""
import json
from pathlib import Path
import sys
from ws13b_differential import verify_sources, compare
expected=json.loads((Path(__file__).resolve().parents[2]/"rust/crates/db/src/models/huddle_observed_matrix.json").read_text())
actual=json.loads(Path(sys.argv[1]).read_text())
verify_sources(actual)
assert actual==expected,"observed Rails corpus regeneration differs"
print(f"Observed Rails corpus: {len(actual['cases'])} sequences regenerated byte-for-byte as JSON values; {actual['random_count']} random; no delivery projection")
