#!/usr/bin/env python3
"""Re-run the pinned Rails oracles from fresh seeds and reject any changed golden bytes."""
import os
import argparse
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[3]
SCRATCH = ROOT / ".scratch/messaging-golden-check"
IMAGE = os.environ.get("PARITY_IMAGE", "triage-reference-d7c7de92")
ORACLES = ["preview", "fragments", "root", "paging", "broadcasts", "thread-memberships", "collection", "room-list", "message-states", "thread-message-reads", "thread-message-writes", "thread-pages", "thread-lifecycle", "thread-content", "forwards", "forward-success", "modern-boosts", "signed-attachments", "boost-pages", "thread-review", "thread-upload-coverage", "client-retries", "avatar-logo-uploads"]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("names", nargs="*", choices=ORACLES)
parser.add_argument("--write", action="store_true", help="regenerate committed vectors from Rails")
options = parser.parse_args()
names = options.names or ORACLES
file_count = 0
for folder in ["db", "files", "out"]:
    (SCRATCH / folder).mkdir(parents=True, exist_ok=True)

# Media records read the files generated by the parity seed, never prior worker scratch.
shutil.copytree(ROOT / "rust/parity/.seed/default/storage", SCRATCH / "files", dirs_exist_ok=True)

for name in names:
    shutil.copyfile(ROOT / "rust/parity/.seed/default/db/production.sqlite3", SCRATCH / "db/production.sqlite3")
    args = ["docker", "run", "--rm", "--cpus", "2", "--name", f"ws8bm-goldens-{name}",
            "--user", f"{os.getuid()}:{os.getgid()}", "--env-file", str(ROOT / "rust/parity/.env.reference"),
            "-e", "RAILS_LOG_LEVEL=warn", "-e", "PARITY_REDIS=1",
            "-v", f"{SCRATCH / 'db'}:/rails/storage/db", "-v", f"{SCRATCH / 'files'}:/rails/storage/files",
            "-v", f"{SCRATCH / 'out'}:/out", "-v", f"{ROOT / 'rust'}:/work:ro", IMAGE,
            "bash", "-c", f"bin/rails runner --skip-executor /work/reference-tools/messaging/{name}.rb /out/{name}.json"]
    run = subprocess.run(args, cwd=ROOT, capture_output=True, text=True)
    (SCRATCH / f"{name}.log").write_text(run.stdout + run.stderr)
    assert run.returncode == 0, f"{name}: reference failed; inspect {SCRATCH / (name + '.log')}"
    for line in run.stdout.splitlines():
        if line.startswith("WS8bm "):
            print(line, flush=True)
    files = [f"{name}.json"] + (["index-template-digest.txt"] if name == "paging" else [])
    for file in files:
        if options.write:
            shutil.copyfile(SCRATCH / "out" / file, ROOT / "rust/vectors/messaging" / file)
        assert (SCRATCH / "out" / file).read_bytes() == (ROOT / "rust/vectors/messaging" / file).read_bytes(), f"{file}: golden bytes differ"
        file_count += 1
print(f"WS8bm golden check: {len(names)} Rails oracles re-run; {file_count} golden files byte-identical", flush=True)
