#!/usr/bin/env python3
"""Re-run the pinned Rails oracles from fresh seeds and reject any changed golden bytes."""
import os
import fcntl
import argparse
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[3]
SCRATCH = ROOT / ".scratch/messaging-golden-check"
IMAGE = os.environ.get("PARITY_IMAGE", "campfire-reference")
image_env = subprocess.check_output(
    ["docker", "image", "inspect", "--format", "{{range .Config.Env}}{{println .}}{{end}}", IMAGE],
    text=True,
)
revision = next(line.removeprefix("GIT_REVISION=") for line in image_env.splitlines()
                if line.startswith("GIT_REVISION="))
assert revision == (ROOT / "rust/parity/reference.sha").read_text().strip(), \
    "reference image revision does not match parity/reference.sha"
ORACLES = ["fresh-github-reference", "thread-cache-stability", "cache-stability", "rendered-dependencies", "cache-reaction-review", "preview", "fragments", "root", "paging", "broadcasts", "thread-memberships", "collection", "room-list", "message-states", "thread-message-reads", "thread-message-writes", "thread-pages", "thread-lifecycle", "thread-content", "forwards", "forward-success", "modern-boosts", "signed-attachments", "boost-pages", "thread-review", "thread-upload-coverage", "client-retries", "avatar-logo-uploads", "jpeg-boundary", "room-components", "github-thread-page", "drive-controllers", "live-chrome", "github-edit-refresh", "cached-csrf", "thread-declarations", "provider-declarations", "legacy-cache", "root-declarations", "validator-declarations", "recipient-declarations", "bot-controller-declarations", "event-reference-declaration", "room-csrf"]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("names", nargs="*", choices=ORACLES)
parser.add_argument("--write", action="store_true", help="regenerate committed vectors from Rails")
options = parser.parse_args()
names = options.names or ORACLES
file_count = 0
SCRATCH.mkdir(parents=True, exist_ok=True)
lock = (SCRATCH / ".lock").open("w")
fcntl.flock(lock, fcntl.LOCK_EX)
for folder in ["db", "files", "out"]:
    (SCRATCH / folder).mkdir(parents=True, exist_ok=True)

# Media records read the files generated by the parity seed, never prior worker scratch.
shutil.copytree(ROOT / "rust/parity/.seed/default/storage", SCRATCH / "files", dirs_exist_ok=True)

for name in names:
    shutil.copyfile(ROOT / "rust/parity/.seed/default/db/production.sqlite3", SCRATCH / "db/production.sqlite3")
    args = ["docker", "run", "--rm", "--cpus", "2", "--name", f"ws8bm-goldens-{name}",
            "--user", f"{os.getuid()}:{os.getgid()}", "--env-file", str(ROOT / "rust/parity/.env.reference"),
            "-e", "RAILS_LOG_LEVEL=warn", "-e", "PARITY_REDIS=1",
            "-e", "PARITY_REFERENCE_SHA=" + revision,
            "-v", f"{SCRATCH / 'db'}:/rails/storage/db", "-v", f"{SCRATCH / 'files'}:/rails/storage/files",
            "-v", f"{SCRATCH / 'out'}:/out", "-v", f"{ROOT / 'rust'}:/work:ro", IMAGE,
            "bash", "-c", f"bin/rails runner --skip-executor /work/reference-tools/messaging/{name}.rb /out/{name}.json"]
    run = subprocess.run(args, cwd=ROOT, capture_output=True, text=True)
    (SCRATCH / f"{name}.log").write_text(run.stdout + run.stderr)
    assert run.returncode == 0, f"{name}: reference failed; inspect {SCRATCH / (name + '.log')}"
    for line in run.stdout.splitlines():
        if line.startswith("WS8bm "):
            print(line, flush=True)
    files = [f"{name}.json"] + (["message-template-digest.txt"] if name == "rendered-dependencies" else []) + (["index-template-digest.txt"] if name == "paging" else [])
    for file in files:
        target = (ROOT / "rust/crates/views/src/messages/rails-template-digest.txt" if file == "message-template-digest.txt"
                  else ROOT / "rust/crates/campfire/src/controllers/messages/rails-index-template-digest.txt" if file == "index-template-digest.txt"
                  else ROOT / "rust/vectors/messaging" / file)
        if options.write:
            shutil.copyfile(SCRATCH / "out" / file, target)
        assert (SCRATCH / "out" / file).read_bytes() == target.read_bytes(), f"{file}: golden bytes differ"
        file_count += 1
print(f"WS8bm golden check: {len(names)} Rails oracles re-run; {file_count} golden files byte-identical", flush=True)
