ARG BASE_IMAGE=campfire-reference
FROM ${BASE_IMAGE}
COPY app/views/users/sidebars/show.html.erb /rails/app/views/users/sidebars/show.html.erb
COPY app/views/layouts/application.html.erb /rails/app/views/layouts/application.html.erb
