FROM ws13-reference:d7c7de92
COPY app/views/users/sidebars/show.html.erb /rails/app/views/users/sidebars/show.html.erb
COPY app/views/layouts/application.html.erb /rails/app/views/layouts/application.html.erb
