require 'json'
texts=["#Ⅷ #² #½ #क् #ᢅ #a‌ #𝟟 #_","<b>hi</b>\nbye","Hi @jack, see https://x.com/a/status/1! #news",'mail a@b.co or visit https://x.com/@jack#frag',"it's <3 (https://x.com/a/status/2).","a<b>\n@c",'short','x'*480,'x'*481,"line\n"*11,"line\n"*12," #中文 #é #á #١٢ #💥 ","é@jack a@b _@c .@jack @0123456789abcdef @shorté",'https://a.test/x?x=1&y=2,;!? @a_ #a_b',"\r\n@a\r #b\t https://a.test/a).",'https://a.test/ahttps://b.test/b!',"https://a.test/one @two #space",'&#39; &amp; <script>bad</script> "quote"',nil]
urls=['see https://x.com/jack/status/20 please','http://twitter.com/jack/status/20','https://www.twitter.com/jack/status/20','https://mobile.x.com/jack/statuses/20','https://x.com/i/status/20','https://x.com/i/web/status/20','https://x.com/jack/status/20/photo/1?s=20&t=abc#frag',(1..6).map { |n| "https://x.com/user#{n}/status/#{n}" }.join(' ')+' again https://x.com/other/status/2','https://x.com/0123456789abcdef/status/20','https://x.com/home https://x.com/jack/status/abc ftp://x.com/jack/status/20','https://x.com/a/status/9999999999999999999999999','https://x.com/a/status/99999999999999999999999999','https://x.com/a/status/12é','HTTPS://X.COM/A/status/12',nil]
htmls=[%q{<p>see <code>https://x.com/jack/status/21</code> and https://x.com/jack/status/22</p><pre><code>https://x.com/jack/status/23</code></pre><p><a href="https://x.com/jack/status/24">the post</a></p>},%q{<div>see https://x.com/jack/status/25<br>thanks</div><p>also https://x.com/jack/status/26</p><p>for this</p>},%q{<p>&amp; <a href="https://x.com/a/status/3?x=1&amp;y=2">label</a></p>},%q{<table><tr><td>https://x.com/a/status/1</td><td>thanks</td></tr></table>},%q{<code><a href="https://x.com/a/status/1">hidden</a></code><a href="https://x.com/b/status/2">visible</a>},nil]
format=texts.map { |text| {text:text,format:Twitter::PostFormatter.format(text).to_s,plain:Twitter::PostFormatter.plain(text).to_s,clamp:Twitter::PostFormatter.clamp?(text)} }
extract=urls.map { |text| {text:text,refs:Twitter::PostUrl.extract(text).map(&:to_h),matches:Twitter::PostUrl.post_url?(text)} }
non_code=htmls.map { |html| text=Twitter::PostUrl.non_code_text(html);{html:html,text:text,refs:Twitter::PostUrl.extract(text).map(&:to_h)} }
File.write(ARGV.fetch(0),JSON.pretty_generate({reference:ENV.fetch("PARITY_REFERENCE_SHA")[0, 8],format:format,extract:extract,non_code:non_code})+"\n")
puts "WS15e X text Rails oracle: #{format.size} formats, #{extract.size} extractions, #{non_code.size} non-code fragments"
