// Replay the pinned Rails surface declarations on real browser/server producers.
import assert from 'node:assert/strict'
import fs from 'node:fs'
import crypto from 'node:crypto'
import { DatabaseSync } from 'node:sqlite'
import { chromium } from 'playwright'
import { network } from './original_browser_network.mjs'
import { visit, waitForController } from './browser_navigation.mjs'
import { fixtureAction } from './ledger_fixture_bridge.mjs'
import { diagnostics } from './browser_diagnostics.mjs'
import { displayedCount as displayed, displayedText, evaluateWithDisplayed } from './selenium_displayed.mjs'
import { viewportFor, resizeOriginal } from './ledger_browser_viewports.mjs'
const base=process.env.WS11UI_BROWSER_URL, selected=process.env.WS11UI_BROWSER_CASE, mutation=process.env.WS11UI_BROWSER_MUTATION||(process.env.WS11UI_BROWSER_CONTROL==='1'?{'audit-filter':'audit-action','icon-colon':'icon-autocomplete','icon-room':'room-header-icon','icon-search':'search-icon','icon-lobehub':'brand-render','workspace-icons':'workspace-custom','unread-pill':'jump-unread','worker-retry':'offline-retry','group-ringing':'huddle-ring','timezone-no-csrf':'timezone-token-guard'}[process.env.WS11UI_BROWSER_CASE]:'')||''
const labels=JSON.parse(fs.readFileSync(process.env.WS11UI_BROWSER_LABELS,'utf8'))
const db=new DatabaseSync(process.env.WS11UI_BROWSER_DATABASE);db.exec('PRAGMA busy_timeout=10000')
const proxy=await network(base)
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--mute-audio',...(selected.startsWith('csp-')?['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']:[])]})
const requests=[]
const file=n=>'test/system/'+n+'_test.rb'
function eq(f,l,a,b){assert.deepEqual(a,b,`${f}:${l}: original assertion`);console.log(`ORIGINAL_ASSERTION ${f}:${l}`)}
function ok(f,l,a){eq(f,l,!!a,true)}
async function pollPresent(locator,timeout){const start=performance.now();do{if(await displayed(locator)>0)return true;await new Promise(resolve=>setTimeout(resolve,20))}while(performance.now()-start<timeout);return false}
async function pollObserved(locator,text,n,{all=false,timeout=2000}={}){
 const start=performance.now();let value
 while((value=await displayed(locator,text,all))!==n){if(performance.now()-start>=timeout)return value;await new Promise(resolve=>setTimeout(resolve,20))}
 return value
}
async function visible(p,f,l,selector,text=null,timeout=2000,all=false){
 const loc=typeof selector==='string'?p.locator(selector):selector,start=performance.now();let value
 while((value=await displayed(loc,text,all))<1){if(performance.now()-start>=timeout)break;await new Promise(resolve=>setTimeout(resolve,20))}
 ok(f,l,value>=1)
}
async function field(p,f,l,locator,value=undefined){
 const candidates=locator.and(p.locator('input:not([type="submit"]):not([type="image"]):not([type="hidden"]):not(:disabled),textarea:not(:disabled),select:not(:disabled)'))
 if(value===undefined)return visible(p,f,l,candidates)
 const start=performance.now();let found=false
 do{for(const node of await candidates.all()){if(await displayed(node)>0&&await node.evaluate(el=>el.value)===value){found=true;break}}if(found)break;await new Promise(resolve=>setTimeout(resolve,20))}while(performance.now()-start<2000)
 ok(f,l,found)
}
async function count(p,f,l,selector,n){eq(f,l,await pollObserved(p.locator(selector),null,n),n)}
async function absent(p,f,l,selector,text=null,{all=false,timeout=2000}={}){const loc=typeof selector==='string'?p.locator(selector):selector;eq(f,l,await pollObserved(loc,text,0,{all,timeout}),0)}
async function absentButton(p,f,l,label){
 const start=performance.now();let value
 do{value=await evaluateWithDisplayed(p,({label},isDisplayed)=>{
  const normalized=el=>(el.textContent||'').replace(/[\t\r\n ]+/g,' ').replace(/^ | $/g,''),has=(el,key)=>el.getAttribute(key)?.includes(label)===true
  const labels=Array.from(document.querySelectorAll('label')).filter(el=>normalized(el).includes(label))
  return Array.from(document.querySelectorAll('button,input[type="submit"],input[type="reset"],input[type="image"],input[type="button"]')).filter(el=>{
   if(el.hasAttribute('disabled')||el.matches(':disabled')||!isDisplayed.call(null,el))return false
   const associated=labels.some(l=>l.getAttribute('for')===el.id&&el.id!==''||l.contains(el))
   const attributes=el.id===label||el.getAttribute('name')===label||['value','title','aria-label'].some(k=>has(el,k))||associated
   const content=el.tagName==='BUTTON'&&(normalized(el).includes(label)||Array.from(el.querySelectorAll('img')).some(img=>has(img,'alt')))
   const image=el.matches('input[type="image"]')&&(has(el,'alt')||has(el,'aria-label'))
   return attributes||content||image
  }).length
 },{label});if(!value)break;await new Promise(resolve=>setTimeout(resolve,20))}while(performance.now()-start<2000)
 eq(f,l,value,0)
}
async function clickDisplayed(locator,options={}){for(const candidate of await locator.all()){if(await displayed(candidate))return candidate.click(options)}throw Error('original interaction has no displayed target')}
async function originalFind(locator){const start=performance.now();do{const found=[];for(const candidate of await locator.all())if(await displayed(candidate))found.push(candidate);if(found.length){assert.equal(found.length,1,'original displayed find must be unambiguous');return found[0]}await new Promise(resolve=>setTimeout(resolve,20))}while(performance.now()-start<2000);throw Error('original displayed find matched no element')}
async function controller(p,n){await waitForController(p,n)}
async function routeMutation(context,pattern,before,after){await context.route(pattern,async route=>{const response=await route.fetch();const body=await response.text();if(!body.includes(before))return route.fulfill({response});console.log(`ORIGINAL_MUTATION served producer ${before}`);const headers={...response.headers()};delete headers['content-encoding'];delete headers['content-length'];await route.fulfill({response,headers,body:body.replaceAll(before,after)});})}
function auditFixture(name){const now=labels['clock.now'];const rows=[['user.ban','User',labels['users.kevin'],'Kevin <kevin@37signals.com>',name==='audit-filter'?{status:['active','banned']}:{}]];if(name==='audit-filter')rows.push(['room.create','Room',labels['rooms.watercooler'],'All Talk',{name:'All Talk'}]);for(const [action,type,id,label,details] of rows)db.prepare('INSERT INTO audit_logs(action,actor_id,actor_label,target_type,target_id,target_label,details,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(action,labels['users.david'],'David <david@37signals.com>',type,id,label,JSON.stringify(details),now,now)}
function surfaceRoomFixtures(){const now=labels['clock.now'];for(const [id,name,type] of [[labels['surface.stage'],'Town Hall','Rooms::Stage'],[labels['surface.board'],'Launch','Rooms::Board']]){db.prepare('INSERT INTO rooms(id,name,type,creator_id,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(id,name,type,labels['users.david'],now,now);db.prepare('INSERT INTO memberships(room_id,user_id,stage_role,created_at,updated_at) VALUES (?,?,?,?,?)').run(id,labels['users.david'],type==='Rooms::Stage'?'host':null,now,now)}}
async function scenario(name,fn,{user='jz',width=(name.startsWith('icon-')||name.startsWith('audit-')||name==='workspace-icons'?1440:1400),height=(name.startsWith('icon-')||name.startsWith('audit-')||name==='workspace-icons'?1000:1400),path='/rooms/'+labels['rooms.designers'],worker=false,csp=false,anonymous=false,noForgery=false}={}){
 if(selected!==name)return
 let context,classContext,groupEnvironment,p,diagnose
 const transport=[]
 try{
  if(name==='icon-room'||name==='group-ringing'){
   classContext=await browser.newContext({viewport:viewportFor(labels,...(name==='icon-room'?[1440,1000]:[1400,1400])),colorScheme:'light'})
   await classContext.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort())
   const initial=await classContext.newPage()
   await signIn(initial,name==='icon-room'?'jz':'david')
   if(name==='icon-room')await join(initial,labels['rooms.designers'])
   if(name==='group-ringing')groupEnvironment=await fixtureAction({action:'environment',values:labels['surface.group_huddle_environment']})
  }
 context=await browser.newContext({viewport:name==='icon-room'||name.startsWith('mobile-')?viewportFor(labels,1400,1400):name==='audit-phone'?viewportFor(labels,1440,1000):viewportFor(labels,width,height),colorScheme:'light'})
 if(!worker)await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort())

 if(csp)await context.addInitScript(()=>document.addEventListener('securitypolicyviolation',e=>{const a=JSON.parse(sessionStorage.getItem('cspViolations')||'[]');a.push({directive:e.effectiveDirective,blocked:e.blockedURI,page:location.pathname,source:e.sourceFile,line:e.lineNumber,sample:e.sample});sessionStorage.setItem('cspViolations',JSON.stringify(a))}))
 if(mutation==='timezone-token-guard')await routeMutation(context,'**/assets/controllers/timezone_controller-*',"if (!document.querySelector(\"meta[name='csrf-token']\")?.getAttribute(\"content\")) return",'if (false) return')
 if(mutation==='timezone-report')await routeMutation(context,'**/assets/controllers/timezone_controller-*','patch(url, {','if (false) patch(url, {')
 if(mutation==='worker-auth-cache')await routeMutation(context,'**/service-worker.js','return url.pathname === OFFLINE_URL || url.pathname.startsWith("/assets/")','return true')
 if(mutation==='offline-retry')await routeMutation(context,'**/offline.html','window.location.reload()',"document.querySelector('h1').textContent='Retry failed'")
 if(mutation==='icon-autocomplete')await routeMutation(context,'**/autocompletable/icons*','OpenAI','Changed icon')
 if(mutation==='audit-action')await routeMutation(context,'**/assets/audit_log-*.css','.audit-log__table code {','.audit-log__table code {\n  opacity: 0;')
 if(mutation==='workspace-custom')await routeMutation(context,'**/assets/icons-*.css','.icon--custom {\n  block-size: 1.2em;','.icon--custom {\n  block-size: 0;')
 if(mutation==='brand-render')await routeMutation(context,'**/assets/icons-*.css','.icon--brand {\n  block-size: 1.2em;','.icon--brand {\n  block-size: 0;')
 if(mutation==='search-icon')await routeMutation(context,'**/assets/icons-*.css','.searches .message--formatted .message__room.message__room--custom::before {\n  content: none;','.searches .message--formatted .message__room.message__room--custom::before {\n  content: "→";')
 if(mutation==='room-header-icon')await routeMutation(context,'**/assets/icons-*.css','.room-header__icon {','.room-header__icon {\n  display: none;')
 p=await context.newPage();p.setDefaultTimeout(10000);if(worker){await visit(p,base+'/offline.html');await context.addCookies([{name:'enable_service_worker',value:'1',url:base}])};diagnose=diagnostics(p)
 p.on('console',m=>{if(m.type()==='error'&&m.text().includes('ERR_BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS'))transport.push(m.text())});p.on('pageerror',e=>transport.push(String(e)));p.on('requestfailed',r=>{if(new URL(r.url()).origin===new URL(base).origin&&new URL(r.url()).pathname.startsWith('/assets/')&&r.failure()?.errorText!=='net::ERR_ABORTED')transport.push(r.failure().errorText)});p.on('response',r=>{if(r.status()>=500)transport.push(r.status()+' '+r.url())})

  if(noForgery)await fixtureAction({action:'forgery-off'})
  if(csp){await visit(p,base+'/');await p.evaluate(()=>sessionStorage.removeItem('cspViolations'))}
  if(name==='csp-surfaces')surfaceRoomFixtures()
  if(!anonymous)await signIn(p,user)
  if(name.startsWith('audit-'))auditFixture(name)
  if(name.startsWith('mobile-')||name==='audit-phone')await resizeOriginal(p,width,height)
  if(path!==null){const response=await visit(p,base+path);assert.equal(response.status(),200,'real initial page')}
  await fn(p,context)
  console.log(`ORIGINAL_CASE ${name}: passed`)
 }catch(e){if(diagnose)await diagnose(e);if(transport.length)throw Error('INVALID_CONTROL transport: '+JSON.stringify(transport),{cause:e});throw e}
 finally{
  if(noForgery)await fixtureAction({action:'forgery-off'})
  if(groupEnvironment)await fixtureAction({action:'environment',values:groupEnvironment.previous})
  if(context)await context.close()
  if(classContext)await classContext.close()
  if(mutation)console.log(`ORIGINAL_PRODUCER_RESTORED ${name}: browser contexts disposed${groupEnvironment?'; original environment restored':''}`)
 }

}
function state(kind,f,l,extra){requests.push({kind,file:f,line:l,...extra})}
async function cable(p){await p.waitForFunction(()=>{const a=Array.from(document.querySelectorAll('turbo-cable-stream-source'));return a.length>=3&&a.every(e=>e.hasAttribute('connected'))},null,{timeout:15000})}
async function signIn(p,user='jz'){await visit(p,base+'/test_session?'+new URLSearchParams({email_address:user+'@37signals.com',password:'secret123456'}));await visible(p,'test/test_helpers/system_test_helper.rb',65,'a.btn','Designers',10000)}
async function join(p,room){await visit(p,base+'/rooms/'+room);await cable(p)}
async function send(p,body){await controller(p,'markdown-autocomplete');await p.getByRole('combobox',{name:'Write a message',exact:true}).fill(body);await p.getByRole('button',{name:'Send Message',exact:true}).click();let row;const start=Date.now();while(!(row=db.prepare('SELECT id,client_message_id FROM messages WHERE markdown_source=? ORDER BY id DESC LIMIT 1').get(body))){if(Date.now()-start>10000)throw Error('real posted message did not persist');await p.waitForTimeout(50)}await p.locator(message(row)).waitFor({timeout:10000});return row}
function message(row){return '#message_'+row.client_message_id}
async function noViolations(p,f,l){eq(f,212,await p.evaluate(()=>JSON.parse(sessionStorage.getItem('cspViolations')||'[]')),[]);console.log(`ORIGINAL_ASSERTION ${f}:${l}`)}
async function mutateController(p,name,method){await controller(p,name);await p.evaluate(({name,method})=>{const el=document.querySelector(`[data-controller~='${name}']`),c=window.Stimulus.getControllerForElementAndIdentifier(el,name);if(typeof c?.[method]!=='function')throw Error('INVALID_CONTROL missing producer '+name+'.'+method);c[method]=()=>{}},{name,method});console.log(`ORIGINAL_MUTATION ${name}.${method}`)}
const A=file('audit_log')
await scenario('audit-filter',async p=>{await visible(p,A,21,'h1','Audit log');await count(p,A,22,'tbody tr',2);await visible(p,A,23,'tbody td code','user.ban');await visible(p,A,24,'tbody td','Kevin <kevin@37signals.com>');await p.locator('select[name="audit_action"]').selectOption('user.ban');await p.getByRole('button',{name:'Filter',exact:true}).click();await count(p,A,29,'tbody tr',1);await visible(p,A,30,'tbody td code','user.ban');const href=await p.getByRole('link',{name:'Export CSV',exact:true}).getAttribute('href');ok(A,33,href.includes('audit_log.csv'));ok(A,34,href.includes('audit_action=user.ban'))},{user:'david',path:'/account/audit_log'})
await scenario('audit-phone',async p=>{await visible(p,A,43,'h1','Audit log');await field(p,A,44,p.getByLabel('Actor',{exact:true}));await visible(p,A,45,'tbody td code','user.ban');eq(A,47,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true)},{user:'david',width:390,height:844,path:'/account/audit_log'})
const I=file('icons')
async function noSuggestions(p,editor,text,site){await editor.fill(text);await p.evaluate(()=>{window.__iconSuggestionFetches=0;if(!window.__iconSuggestionFetchWrapped){window.__iconSuggestionFetchWrapped=true;window.fetch=((original)=>(...args)=>{const url=String(args[0]?.url||args[0]);if(!url.includes('/autocompletable/'))return original(...args);window.__iconSuggestionFetches++;return original(...args).finally(()=>window.__iconSuggestionFetches--)})(window.fetch.bind(window))}const e=document.querySelector('#message_markdown_source');const c=window.Stimulus.getControllerForElementAndIdentifier(e.closest('[data-controller~="markdown-autocomplete"]'),'markdown-autocomplete');c.handlers.forEach(h=>h.updateWithContentAndPosition(e.value,e.selectionStart))});await p.waitForFunction(()=>window.__iconSuggestionFetches===0,null,{timeout:10000});await p.waitForTimeout(100);await absent(p,I,133,'suggestion-option',null,{timeout:0});console.log(`ORIGINAL_ASSERTION ${I}:${site}`)}
async function filter(p,row){return p.locator(message(row)+' img.icon--brand').first().evaluate(el=>getComputedStyle(el).filter)}
async function rendered(p,row,alt,site){const [w,h]=await p.locator(message(row)+` img.icon--brand[alt='${alt}']`).first().evaluate(el=>{const r=el.getBoundingClientRect();return [r.width,r.height]});ok(I,144,w>0);ok(I,145,h>0);console.log(`ORIGINAL_ASSERTION ${I}:${site}`)}
await scenario('icon-colon',async(p,context)=>{await controller(p,'markdown-autocomplete');const meta=p.locator('meta[name="brand-icon-names"][content*="openai"]');eq(I,21,(await meta.count())-(await displayed(meta))>0,true);const e=p.getByRole('combobox',{name:'Write a message',exact:true});for(const [t,site] of [['::',25],['12:30',26],['http://',27]])await noSuggestions(p,e,t,site);await e.fill(':open');await visible(p,I,30,'suggestion-option','OpenAI');await e.press('Enter');await field(p,I,32,e,':openai: ');eq(I,33,db.prepare('SELECT COUNT(*) AS n FROM messages WHERE markdown_source=?').get(':openai: ').n,0);await p.getByRole('button',{name:'Send Message',exact:true}).click();await visible(p,I,36,'.message img.icon--brand');const row=db.prepare('SELECT id,client_message_id FROM messages WHERE markdown_source=? ORDER BY id DESC LIMIT 1').get(':openai: ');assert.ok(row);state('message',I,37,{body:':openai: ',id:row.id});await visible(p,I,38,message(row)+'.message--emoji');await visible(p,I,39,message(row)+' img.icon--brand');eq(I,40,await filter(p,row),'none');await p.emulateMedia({colorScheme:'dark'});eq(I,43,await p.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches),true);await visible(p,I,44,message(row)+' img.icon--brand');eq(I,45,await filter(p,row),'invert(1)')})
await scenario('icon-room',async p=>{await controller(p,'markdown-autocomplete');await controller(p,'icon-field');await p.getByLabel('Icon',{exact:true}).fill(':open');await visible(p,I,54,'suggestion-option','OpenAI');await p.locator('suggestion-option').filter({hasText:'OpenAI'}).click();await p.waitForFunction(()=>document.querySelector('#room_icon_name').value===':openai: ',null,{timeout:2000});await field(p,I,56,p.getByLabel('Icon',{exact:true}),':openai: ');await visible(p,I,57,"[data-icon-field-target='preview'] img.icon-avatar");await clickDisplayed(p.locator('button.btn--reversed'));await visible(p,I,60,'.room-header__name','All Pets');await visible(p,I,61,'.room-header__identity img.icon-avatar');await visible(p,I,62,`#list_rooms_open_${labels['rooms.pets']} .sidebar-item__icon--custom img.icon-avatar`);eq(I,63,await p.locator(`#list_rooms_open_${labels['rooms.pets']} .sidebar-item__icon`).first().evaluate(el=>getComputedStyle(el,'::before').content),'none');eq(I,64,await p.locator(`#list_rooms_open_${labels['rooms.hq']} .sidebar-item__icon`).first().evaluate(el=>getComputedStyle(el,'::before').content),'"#"')},{user:'david',path:'/rooms/opens/'+labels['rooms.pets']+'/edit'})
await scenario('icon-search',async p=>{db.prepare('UPDATE rooms SET icon_name=? WHERE id=?').run('openai',labels['rooms.designers']);for(const [room,body,key] of [['designers','Cartography atlas rendezvous','icon-search-room'],['hq','Cartography ledger rendezvous','plain-search-room']])await fixtureAction({action:'message',room:labels['rooms.'+room],creator:labels['users.david'],body,key});await visit(p,base+'/searches?q=Cartography%20rendezvous');await visible(p,I,75,'#search-results .message__room--custom img.icon-avatar');await visible(p,I,76,'#search-results .message__room:not(.message__room--custom)');eq(I,77,await p.locator('#search-results .message__room--custom').first().evaluate(el=>getComputedStyle(el,'::before').content),'none');eq(I,78,await p.locator('#search-results .message__room:not(.message__room--custom)').first().evaluate(el=>getComputedStyle(el,'::before').content),'"→"')})
await scenario('icon-lobehub',async p=>{const row=await send(p,'Ship :xai: and :microsoft: today');await visible(p,I,85,'.message img.icon--brand');state('message',I,87,{body:'Ship :xai: and :microsoft: today',id:row.id});await count(p,I,88,message(row)+' img.icon--brand',2);await rendered(p,row,':xai:',89);await rendered(p,row,':microsoft:',90);eq(I,91,await filter(p,row),'none');await p.emulateMedia({colorScheme:'dark'});eq(I,94,await p.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches),true);await count(p,I,95,message(row)+' img.icon--brand',2);await rendered(p,row,':xai:',96);await rendered(p,row,':microsoft:',97);eq(I,98,await filter(p,row),'invert(1)')})
const M=file('mobile_layout')
await scenario('mobile-outside',async p=>{for(const path of ['/users/me/profile','/account/edit']){await visit(p,base+path);await visible(p,M,119,'#nav a','Go Back',2000,true);await absentButton(p,M,120,'Open workspace navigation')}},{width:375,height:812,path:null})
await scenario('mobile-destinations',async p=>{for(const [destination,title] of [['People','People'],['Agents','Agents'],['Work threads','Work'],['Saved','Saved for later'],['Scheduled','Scheduled messages'],['Activity inbox','Activity inbox']]){await visible(p,M,132,'#main-content');await p.getByRole('button',{name:'Open workspace navigation',exact:true}).click();await visible(p,M,134,'#sidebar.open');await p.locator('#sidebar').getByRole('link',{name:destination,exact:true}).click();await absent(p,M,136,'#sidebar.open');await p.waitForFunction(title=>document.title.includes(title),title,{timeout:10000});ok(M,137,(await p.title()).includes(title));eq(M,144,await p.evaluate(()=>Array.from(document.querySelectorAll('#nav a,#nav button')).filter(e=>e.getClientRects().length>0&&!e.closest('.global-search,.help-menu')).map(e=>e.getAttribute('aria-label')||e.textContent.trim())),['Open workspace navigation']);await p.getByRole('button',{name:'Open workspace navigation',exact:true}).click();await visible(p,M,147,'#sidebar.open');await visible(p,M,148,"#sidebar .workspace-destinations a[aria-current='page']",destination,10000);await count(p,M,149,"#sidebar .workspace-destinations a[aria-current='page']",1);await p.keyboard.press('Escape');await absent(p,M,151,'#sidebar.open')}},{width:375,height:812,path:'/activity'})
const SW=file('service_worker')
await scenario('worker-cache',async p=>{await controller(p,'messages');await p.waitForFunction(async()=>{const r=await navigator.serviceWorker.ready;return !!r.active&&!!navigator.serviceWorker.controller},null,{timeout:15000});await join(p,labels['rooms.watercooler']);const urls=await p.evaluate(async()=>{const urls=[];for(const n of await caches.keys())for(const r of await(await caches.open(n)).keys())urls.push(new URL(r.url).pathname);return urls});ok(SW,20,urls.includes('/offline.html'));ok(SW,21,urls.some(x=>x.startsWith('/assets/')));eq(SW,24,urls.filter(x=>x!='/offline.html'&&!x.startsWith('/assets/')),[])},{worker:true})
await scenario('worker-retry',async p=>{await visible(p,SW,34,'h1','You’re offline — reconnecting…');await visible(p,SW,35,'#offline-retry','Try again now');await visible(p,SW,36,'[role="status"]','automatically when your connection returns');await p.getByRole('button',{name:'Try again now',exact:true}).click();await visible(p,SW,40,'h1','You’re offline — reconnecting…')},{worker:true,anonymous:true,path:'/offline.html'})
const Z=file('timezone_detection')
// ActiveSupport String#blank?: the original settle guard fails only for a present zone.
function zonePresent(zone){return zone!==null&&!/^[\t\n\v\f\r \u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]*$/.test(zone)}
await scenario('timezone-no-csrf',async p=>{await join(p,labels['rooms.designers']);db.prepare('UPDATE users SET time_zone=NULL WHERE id=?').run(labels['users.jz']);await visit(p,base+'/rooms/'+labels['rooms.watercooler']);await controller(p,'timezone');assert.equal(await p.locator('meta[name="csrf-token"]').count(),0,'original disabled-forgery producer setup');const start=performance.now();while(performance.now()-start<2000){eq(Z,51,zonePresent(db.prepare('SELECT time_zone FROM users WHERE id=?').get(labels['users.jz']).time_zone),false);await p.waitForTimeout(100)}eq(Z,54,db.prepare('SELECT time_zone FROM users WHERE id=?').get(labels['users.jz']).time_zone,null);console.log(`ORIGINAL_ASSERTION ${Z}:14`)},{noForgery:true,path:null})
await scenario('timezone-once',async p=>{await controller(p,'timezone');const start=performance.now();while(!zonePresent(db.prepare('SELECT time_zone FROM users WHERE id=?').get(labels['users.jz']).time_zone)){if(performance.now()-start>=10000)throw Error(`${Z}:60: original assertion expected zone`);await p.waitForTimeout(100)}const zone=await p.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone);eq(Z,24,db.prepare('SELECT time_zone FROM users WHERE id=?').get(labels['users.jz']).time_zone,zone);state('timezone',Z,24,{zone})})
const U=file('unread_divider')
function markBefore(room,id){const row=db.prepare('SELECT created_at FROM messages WHERE id=?').get(id);const prev=db.prepare('SELECT id FROM messages WHERE room_id=? AND thread_id IS NULL AND (created_at,id)<(?,?) ORDER BY created_at DESC,id DESC LIMIT 1').get(room,row.created_at,id);db.prepare('UPDATE memberships SET unread_at=?,last_read_message_id=?,connected_at=NULL,connections=0 WHERE room_id=? AND user_id=?').run(row.created_at,prev?.id||null,room,labels['users.jz'])}
async function createUnread(p,n,kind){const room=labels['rooms.designers'];await join(p,room);db.prepare('UPDATE memberships SET connected_at=NULL,connections=0 WHERE room_id=? AND user_id=?').run(room,labels['users.jz']);await join(p,labels['rooms.hq']);const messages=[];for(let i=0;i<n;i++){const body=kind==='few'?(i===0?'Fresh one':'Fresh two'):kind==='many'?`Catch-up ${i}`:kind==='pill'?`Pill ${i}\nsecond line`:i===0?'First unread off page':`Later ${i-1}`;const client=kind==='few'?`divider-few-${i+1}`:kind==='many'?`divider-many-${i}`:kind==='pill'?`divider-pill-${i}`:i===0?'divider-offpage-first':`divider-offpage-${i-1}`;messages.push({room,creator:labels['users.kevin'],body,key:client})}const result=await fixtureAction({action:'messages',messages});await join(p,room);return result.messages[0].id}
async function divider(p,id,site){eq(U,123,await p.evaluate(()=>document.getElementById('unread-divider').nextElementSibling?.dataset.messageId),String(id));console.log(`ORIGINAL_ASSERTION ${U}:${site}`)}
await scenario('unread-few',async p=>{const id=await createUnread(p,2,'few');await visible(p,U,19,'#unread-divider',/new messages/i,5000);await divider(p,id,20);ok(U,133,await p.locator('.messages').first().evaluate(el=>el.scrollHeight-el.scrollTop-el.clientHeight<100));console.log(`ORIGINAL_ASSERTION ${U}:21`)},{path:null})
await scenario('unread-many',async p=>{await createUnread(p,7,'many');await visible(p,U,35,'#unread-divider',null,5000);const g=await p.evaluate(()=>{const list=document.querySelector('.messages').getBoundingClientRect(),d=document.getElementById('unread-divider').getBoundingClientRect();return {top:d.top-list.top,listHeight:list.height}});ok(U,45,g.top<g.listHeight/2)},{path:null})
await scenario('unread-pill',async p=>{await createUnread(p,25,'pill');await visible(p,U,61,'#unread-divider',null,5000);await p.evaluate(()=>{const l=document.querySelector('.messages');l.scrollTop=l.scrollHeight});await visible(p,U,64,'#jump-to-unread',null,5000);if(mutation==='jump-unread')await mutateController(p,'messages','jumpToUnread');await p.getByRole('button',{name:'Jump to unread',exact:true}).click();await absent(p,U,70,'#jump-to-unread',null,{timeout:5000});await visible(p,U,71,'#unread-divider')},{path:null})
await scenario('unread-offpage',async p=>{const id=await createUnread(p,42,'offpage');await absent(p,U,86,'.message','First unread off page');const pill=p.getByRole('link',{name:'Jump to unread',exact:true});await pill.waitFor();ok(U,88,(await pill.getAttribute('href')).includes('message_id='+id));markBefore(labels['rooms.designers'],id);await pill.click();await visible(p,U,94,'#unread-divider',null,5000);await divider(p,id,95)},{path:null})
await scenario('unread-menu',async p=>{await join(p,labels['rooms.designers']);const row=db.prepare('SELECT id,client_message_id FROM messages WHERE room_id=? AND thread_id IS NULL ORDER BY created_at,id LIMIT 1 OFFSET 1').get(labels['rooms.designers']);await clickDisplayed(p.locator(message(row)+' [data-message-edit-format], '+message(row)+' [data-reply-target="body"]'),{button:'right'});await visible(p,'test/test_helpers/system_test_helper.rb',141,'[data-message-actions-target="menu"]',null,10000);await visible(p,'test/test_helpers/system_test_helper.rb',142,'.message[data-message-actions-open]');await p.getByRole('menuitem',{name:'Mark unread',exact:true}).click();await visible(p,'test/test_helpers/system_test_helper.rb',131,`.rooms a.unread`,db.prepare('SELECT name FROM rooms WHERE id=?').get(labels['rooms.designers']).name,5000);console.log(`ORIGINAL_ASSERTION ${U}:104`);await visit(p,base+'/rooms/'+labels['rooms.designers']);await visible(p,U,107,'#unread-divider',null,5000);await divider(p,row.id,108)},{path:null})
const W=file('workspace_icons')
await scenario('workspace-icons',async(p,context)=>{await p.locator('#workspace_icon_name').fill('acme');await p.locator('#workspace_icon_title').fill('Acme Corp');await p.locator('#workspace_icon_image').setInputFiles('/work/rust/fixtures/files/workspace_icons/clean.svg');await p.getByRole('button',{name:'Upload icon',exact:true}).click();await visible(p,W,24,'code',':acme:');await visible(p,W,25,"img[src='/icons/acme']");await join(p,labels['rooms.designers']);const row=await send(p,'Ship it with :acme: today');await visible(p,W,29,"img.icon--custom[src='/icons/acme'][alt=':acme:']");state('message',W,30,{body:'Ship it with :acme: today',id:row.id});await visible(p,W,33,message(row)+" img.icon--custom[src='/icons/acme'][alt=':acme:']");await p.emulateMedia({colorScheme:'dark'});await visible(p,W,38,message(row)+" img.icon--custom[src='/icons/acme']");await p.emulateMedia({colorScheme:'light'});await visit(p,base+'/account/icons');p.once('dialog',d=>d.accept());await p.locator('li').filter({hasText:':acme:'}).locator('button[type="submit"]').click();await absent(p,W,47,'code',':acme:');await join(p,labels['rooms.designers']);await absent(p,W,51,message(row)+' img.icon--custom',null,{all:true});await visible(p,W,52,message(row),'Ship it with :acme: today')},{user:'david',path:'/account/icons'})
const P=file('people_group_dms')
await scenario('group-ringing',async p=>{await cable(p);await controller(p,'huddle-invitation');if(mutation==='huddle-ring'){await p.evaluate(()=>{const el=document.querySelector('[data-controller~="huddle-invitation"]');const c=window.Stimulus.getControllerForElementAndIdentifier(el,'huddle-invitation');c.generation=Symbol()});console.log('ORIGINAL_MUTATION huddle-invitation subscription generation')}await fixtureAction({action:'group-huddle',users:['david','jason','kevin'].map(u=>labels['users.'+u]),session:labels['sessions.david_safari']});await visible(p,P,357,'#huddle-invitation:not([hidden])','David started a huddle',10000);for(const [user,line] of [['jason',360],['kevin',361]]){eq(P,line,!!db.prepare('SELECT 1 FROM activity_items WHERE user_id=? AND event_type=?').get(labels['users.'+user],'huddle_started'),true);state('huddle-activity',P,line,{user})}},{user:'jason',width:1400,height:1400})
const C=file('content_security_policy')
function totp(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of secret.toUpperCase())bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2)));const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(new Date(labels['clock.now']).getTime()/30000)));const digest=crypto.createHmac('sha1',key).update(counter).digest(),o=digest.at(-1)&15;return String((digest.readUInt32BE(o)&0x7fffffff)%1000000).padStart(6,'0')}
await scenario('csp-login',async p=>{await p.locator('#email_address').fill('jz@37signals.com');await p.locator('#password').fill('secret123456');await p.locator('button[name="log_in"]').click();await visible(p,C,65,'h1','Set up two-step sign-in',10000);const secret=(await displayedText(await originalFind(p.locator('#two_factor_manual_key')))).replace(/\s+/g,'');await p.getByLabel('Authenticator code',{exact:true}).fill(totp(secret));await p.getByRole('button',{name:'Verify and continue',exact:true}).click();await visible(p,C,70,'h1','Save your backup codes',10000);await p.getByRole('link',{name:'Continue',exact:true}).click();await visible(p,C,77,"aside#sidebar nav[aria-label='Your workspace']",null,10000);await visible(p,C,78,'aside#sidebar a.workspace-user','JZ',10000);await noViolations(p,C,79)},{anonymous:true,csp:true,width:1400,height:1000,path:'/session/new'})
async function failedHuddle(p,lines){await p.getByRole('button',{name:'Join huddle',exact:true}).click();await visible(p,C,lines[0],'#channel-huddle:not([hidden])',null,10000);if(await pollPresent(p.locator("#channel-huddle[data-state='prejoin']"),5000)){await visible(p,C,lines[1],"[data-huddle-target='checkJoin']:not([disabled])",null,20000);await p.locator("[data-huddle-target='checkJoin']").click()}await p.locator("#channel-huddle[data-state='failed']").waitFor({state:'attached',timeout:15000});ok(C,lines[2],await p.locator("#channel-huddle[data-state='failed']").count()>0)}
await scenario('csp-main',async(p,context)=>{await field(p,C,86,p.locator('#email_address'));await signIn(p,'jz');eq(C,88,(await fixtureAction({action:'huddle-configured'})).configured,true);await join(p,labels['rooms.designers']);eq(C,91,await p.locator("[data-controller~='drive-share']").count()>0,true);eq(C,92,await p.locator('#channel-huddle').count()>0,true);await send(p,'CSP check with **bold**, `code`, and a list:\n\n- one\n- two\n\n```ruby\nputs 1\n```');await visible(p,C,95,'.message__body strong','bold');await visible(p,C,96,'.message__body pre','puts 1');await failedHuddle(p,[99,101,105]);await visit(p,base+'/users/me/profile');await visible(p,C,108,'h2','GitHub');await visit(p,base+'/rooms/'+labels['rooms.designers']+'/events/new');await visible(p,C,111,'form');await noViolations(p,C,113)},{anonymous:true,path:'/session/new',csp:true,width:1400,height:1000})
await scenario('csp-turbo',async p=>{await join(p,labels['rooms.designers']);await p.evaluate(path=>{window.cspTurboMarker=true;Turbo.visit(path)},'/rooms/'+labels['rooms.designers']+'/events/new');await visible(p,C,122,"form[data-controller~='event-time-zone']");eq(C,123,await p.evaluate(()=>window.cspTurboMarker===true),true);const zone=await p.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone);ok(C,131,zone.length>0);await visible(p,C,132,"[data-event-time-zone-target='label']",zone);eq(C,133,await p.locator("[data-event-time-zone-target='field']").inputValue(),zone);await noViolations(p,C,135)},{csp:true,width:1400,height:1000,path:null})
await scenario('csp-inline',async p=>{await join(p,labels['rooms.designers']);await p.evaluate(()=>{const script=document.createElement('script');script.textContent='window.cspProbeRan = true';document.body.append(script)});const start=Date.now();let v=[];while(!v.length&&Date.now()-start<5000){v=await p.evaluate(()=>JSON.parse(sessionStorage.getItem('cspViolations')||'[]'));await p.waitForTimeout(100)}ok(C,149,v.some(v=>String(v.directive).startsWith('script-src')));eq(C,151,await p.evaluate(()=>window.cspProbeRan===true),false)},{csp:true,width:1400,height:1000,path:null})
await scenario('csp-surfaces',async p=>{await join(p,labels['rooms.designers']);await failedHuddle(p,[163,165,169]);await join(p,labels['surface.stage']);await visible(p,C,172,'.room--current','Town Hall');await join(p,labels['surface.board']);await visible(p,C,175,'.board__header h1','Launch');await visit(p,base+'/searches');await visible(p,C,178,'#message-area');await visit(p,base+'/account/edit');await visible(p,C,181,'#account_users');await join(p,labels['rooms.designers']);await controller(p,'profile-card');await p.locator('#message_0001 .message__avatar a').click();await visible(p,C,187,'#profile-card-popover:not([hidden])',null,10000);await visible(p,C,189,'#user_card .profile-card__name','Jason');await noViolations(p,C,192)},{user:'david',csp:true,width:1400,height:1000,path:null})
console.log('ORIGINAL_STATE_REQUESTS '+JSON.stringify(requests))
await browser.close();await new Promise(resolve=>proxy.close(resolve));db.close()
