#!/usr/bin/env python3
"""Emit Rails' named zones/accepted TZInfo identifiers and TranslationsHelper table from goldens."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
data = json.loads((root / "crates/views/tests/golden/core/helpers.json").read_text())
quote = lambda text: json.dumps(text, ensure_ascii=False)
zones = root / "crates/views/src/time"
zones.mkdir(exist_ok=True)
source = "// Generated by reference-tools/views/core/generate_tables.py from our Rails helper vectors.\n"
source += "pub const MAPPING: &[(&str, &str)] = &[\n"
source += "".join(f"    ({quote(name)}, {quote(identifier)}),\n" for name, identifier in data["zone_mapping"])
source += "];\npub const IDENTIFIERS: &[&str] = &[\n"
source += "".join(f"    {quote(identifier)},\n" for identifier in data["tz_identifiers"])
source += "];\n"
(zones / "rails_zones.rs").write_text(source)
source = "// Generated by reference-tools/views/core/generate_tables.py from our Rails helper vectors.\n"
source += "pub const TRANSLATIONS: &[(&str, &[(&str, &str)])] = &[\n"
for key, translations in data["translations"].items():
    source += f"    ({quote(key)}, &[\n"
    source += "".join(f"        ({quote(language)}, {quote(text)}),\n" for language, text in translations["entries"])
    source += "    ]),\n"
source += "];\n"
(root / "crates/views/src/helpers/translations_table.rs").write_text(source)
print(f"Generated {len(data['zone_mapping'])} zone names, {len(data['tz_identifiers'])} identifiers and {len(data['translations'])} translation keys")
