//! Our `config/routes.rb`, for the app and its views: the route table the app dispatches on
//! ([`TABLE`]) and a function per named route that builds its path the way the Rails `*_path`
//! helper does (`campfire_routes::room(1)` is `room_path(1)`: the Rails name without `_path`).
//!
//! Both are generated by `build.rs` from `routes.json`, which `reference-tools/routes/routes.rb`
//! dumps from the reference app; regenerate it after a change to `config/routes.rb`. Path
//! parameters are escaped like Journey escapes them, `(.:format)` and query strings go through
//! [`NamedRoute::path_with`], and the `direct` routes (Ruby blocks, not Journey routes) are
//! written by hand below.

use std::fmt::{Display, Write as _};

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

/// One row of `bin/rails routes`.
#[derive(Debug)]
pub struct TableRoute {
    pub verb: &'static str,
    /// The Journey spec, e.g. `/rooms/:room_id/messages(.:format)`.
    pub spec: &'static str,
    /// `controller#action`.
    pub endpoint: &'static str,
    pub name: Option<&'static str>,
    /// `defaults:` other than the controller and action.
    pub defaults: &'static [(&'static str, &'static str)],
    pub action: ActionStatus,
}

/// Whether the reference can run a route's action.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActionStatus {
    /// The controller defines the action method.
    Defined,
    /// No method, but a template, which `ActionController::ImplicitRender` renders.
    Implicit,
    /// Declared by `resources` but not defined: `AbstractController::ActionNotFound`, a 404.
    ActionNotFound,
    /// The controller constant doesn't load: a 500.
    MissingController,
}

/// A named route's path, split where arguments go.
#[derive(Debug)]
pub struct NamedRoute {
    pub name: &'static str,
    pub spec: &'static str,
    pub segments: &'static [Segment],
    /// `defaults: { format: :json }`: asking for this format adds no suffix, as in Rails.
    pub default_format: Option<&'static str>,
}

#[derive(Debug)]
pub enum Segment {
    Literal(&'static str),
    /// `:param`, escaped as a path segment (`/` becomes `%2F`).
    Param {
        name: &'static str,
        default: Option<&'static str>,
    },
    /// `*glob`, escaped as a path (`/` stays).
    Glob {
        name: &'static str,
        default: Option<&'static str>,
    },
}

impl NamedRoute {
    /// The path for these arguments, in the order the Rails helper takes them positionally.
    pub fn path(&self, args: &[&dyn Display]) -> String {
        self.path_with(args, None, &[])
    }

    /// `name_path(*args, format: format, **query)`. Nil extra query values are dropped;
    /// an explicit nil path parameter overrides its default and fails route generation.
    pub fn path_with(
        &self,
        args: &[&dyn Display],
        format: Option<&str>,
        query: &[(&str, Option<&str>)],
    ) -> String {
        // ActionDispatch::Routing::RouteSet::UrlHelper#handle_positional_args:
        // with fewer arguments than path parts, remove defaulted parts. Explicit options
        // always remove their parts before assigning positions; format is the last part.
        let parts: Vec<_> = self
            .segments
            .iter()
            .filter_map(|segment| match segment {
                Segment::Param { name, default } | Segment::Glob { name, default } => {
                    Some((*name, *default))
                }
                _ => None,
            })
            .collect();
        let optimized = args.len() == parts.len() && format.is_none() && query.is_empty();
        let mut positional_parts: Vec<_> = parts
            .iter()
            .filter(|(name, default)| {
                (args.len() >= parts.len() || default.is_none())
                    && !query.iter().any(|(key, _)| key == name)
            })
            .map(|(name, _)| *name)
            .collect();
        if self.spec.ends_with("(.:format)") && format.is_none() {
            positional_parts.push("format");
        }
        let positional: Vec<_> = positional_parts
            .iter()
            .zip(args)
            .map(|(name, arg)| (*name, arg.to_string()))
            .collect();
        let mut path = String::new();
        for segment in self.segments {
            match segment {
                Segment::Literal(literal) => path.push_str(literal),
                Segment::Param { name, default } | Segment::Glob { name, default } => {
                    let value = if let Some((_, value)) = query.iter().find(|(key, _)| key == name)
                    {
                        value.map(str::to_string)
                    } else {
                        positional
                            .iter()
                            .find(|(key, _)| key == name)
                            .map(|(_, value)| value.clone())
                            .or_else(|| default.map(str::to_string))
                    }
                    .unwrap_or_else(|| panic!("{}_path: missing {name}", self.name));
                    assert!(
                        !optimized || !value.is_empty(),
                        "{}_path: missing {name}",
                        self.name
                    );
                    path.push_str(&escape(&value, matches!(segment, Segment::Glob { .. })));
                }
            }
        }
        let format = format.or_else(|| {
            positional
                .iter()
                .find(|(key, _)| *key == "format")
                .map(|(_, value)| value.as_str())
        });
        if let Some(format) = format
            && self.spec.ends_with("(.:format)")
            && Some(format) != self.default_format
        {
            path.push('.');
            path.push_str(&escape(format, false));
        }
        let unused: Vec<_> = query
            .iter()
            .copied()
            .filter(|(key, _)| !parts.iter().any(|(name, _)| name == key))
            .collect();
        with_query(path, &unused)
    }
}

/// `path?` + `Hash#to_query` of the pairs whose value isn't `None`: each `key=value` CGI-escaped,
/// the pairs sorted, joined with `&`. No `?` when nothing is left.
pub fn with_query(mut path: String, query: &[(&str, Option<&str>)]) -> String {
    let mut pairs: Vec<String> = query
        .iter()
        .filter_map(|(key, value)| Some(format!("{}={}", cgi_escape(key), cgi_escape((*value)?))))
        .collect();
    if pairs.is_empty() {
        return path;
    }
    pairs.sort();
    path.push('?');
    path.push_str(&pairs.join("&"));
    path
}

/// `Journey::Router::Utils.escape_segment` (and `escape_path` when `/` is allowed): everything
/// but RFC 3986's unreserved and sub-delims characters, `:` and `@` is percent-encoded.
pub fn escape(value: &str, keep_slash: bool) -> String {
    let mut escaped = String::with_capacity(value.len());
    for byte in value.bytes() {
        let keep = byte.is_ascii_alphanumeric()
            || b"-._~!$&'()*+,;=:@".contains(&byte)
            || (keep_slash && byte == b'/');
        if keep {
            escaped.push(byte as char);
        } else {
            write!(escaped, "%{byte:02X}").unwrap();
        }
    }
    escaped
}

/// `CGI.escape`: letters, digits and `_.-~` stay, a space becomes `+`, the rest is encoded.
pub fn cgi_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b' ' => escaped.push('+'),
            b if b.is_ascii_alphanumeric() || b"_.-~".contains(&b) => escaped.push(b as char),
            b => write!(escaped, "%{b:02X}").unwrap(),
        }
    }
    escaped
}

/// `direct :fresh_user_avatar`: `user_avatar_path(user.avatar_token, v: user.updated_at.to_fs(:number))`.
pub fn fresh_user_avatar(avatar_token: impl Display, updated_at_number: impl Display) -> String {
    USER_AVATAR.path_with(
        &[&avatar_token],
        None,
        &[("v", Some(&updated_at_number.to_string()))],
    )
}

/// `direct :fresh_account_logo`: `account_logo_path(v: Current.account&.updated_at&.to_fs(:number),
/// size: options[:size])`. `v` is `None` without an account.
pub fn fresh_account_logo(v: Option<&str>, size: Option<&str>) -> String {
    ACCOUNT_LOGO.path_with(&[], None, &[("v", v), ("size", size)])
}

/// The SPA's logo source or first-frame PNG, versioned by the attached blob.
pub fn workspace_logo(blob_id: i64, still: bool) -> String {
    ACCOUNT_LOGO.path_with(
        &[],
        None,
        &[
            ("v", Some(&blob_id.to_string())),
            (if still { "still" } else { "animated" }, Some("1")),
        ],
    )
}

/// The workspace banner, versioned by the attached blob rather than the account timestamp.
pub fn fresh_account_banner(blob_id: i64, still: bool) -> String {
    format!(
        "/account/banner?v={blob_id}{}",
        if still { "&still=1" } else { "" }
    )
}

#[cfg(test)]
mod tests;
