//! Byte comparisons with our Rails output, generated by reference-tools/views/core/run.sh.
use askama::Template;
use campfire_views::{AccountSummary, CurrentUser, Platform, ViewContext, helpers as h, layouts};
use serde_json::Value;

mod review;
#[path = "../../../test-support/asset_goldens.rs"]
mod asset_goldens;

fn fixture(path: &str) -> String {
    std::fs::read_to_string(format!(
        "{}/tests/golden/core/{path}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap()
}

fn facts() -> Value {
    serde_json::from_str(&fixture("facts.json")).unwrap()
}

fn context<'a>(
    user: Option<&str>,
    asset: &'a dyn Fn(&str) -> String,
    signer: &'a dyn Fn(&[&str]) -> String,
    styles: &'a str,
) -> ViewContext<'a> {
    let facts = facts();
    let current_user = user.map(|name| {
        let user = &facts["users"][name];
        CurrentUser {
            id: user["id"].as_i64().unwrap(),
            name: user["name"].as_str().unwrap().into(),
            administrator: user["administrator"].as_bool().unwrap(),
            bot: user["bot"].as_bool().unwrap(),
            avatar_url: user["avatar_path"].as_str().unwrap().into(),
            preferences: layouts::UserPreferences {
                tour_completed: user["tour_completed"].as_bool().unwrap(),
                ..Default::default()
            },
        }
    });
    let recent_searches = user
        .map(|name| {
            facts["users"][name]["searches"]
                .as_array()
                .unwrap()
                .iter()
                .map(|search| layouts::RecentSearch {
                    id: search["id"].as_i64().unwrap(),
                    query: search["query"].as_str().unwrap().into(),
                })
                .collect()
        })
        .unwrap_or_default();
    let env = include_str!("../../../parity/.env.reference");
    ViewContext {
        current_user,
        account: AccountSummary {
            name: "37signals".into(),
            logo_url: facts["account"]["logo_path"].as_str().unwrap().into(),
            has_logo: false,
        },
        flash_notice: None,
        flash_alert: None,
        platform: Platform {
            mac: true,
            chrome: true,
            desktop: true,
            browser: "Chrome".into(),
            operating_system: "macOS".into(),
            ..Default::default()
        },
        vapid_public_key: Some(
            env.lines()
                .find_map(|line| line.strip_prefix("VAPID_PUBLIC_KEY="))
                .unwrap()
                .into(),
        ),
        asset_path: asset,
        importmap_tags: campfire_assets::javascript_importmap_tags(),
        stylesheet_tags: styles,
        custom_styles: None,
        cable_url: "/cable".into(),
        base_url: "http://campfire.test".into(),
        request_url: "http://campfire.test/".into(),
        referrer: None,
        last_room_visited_id: None,
        app_version: "parity".into(),
        signed_stream_name: signer,
        time_zone: campfire_views::time::Zone::utc(),
        chrome: layouts::Chrome {
            service_worker_auto_register: true,
            brand_icon_names: facts["brand_icon_names"]
                .as_str()
                .unwrap()
                .split(',')
                .map(str::to_string)
                .collect(),
            recent_searches,
            ..Default::default()
        },
    }
}

fn compare(name: &str, actual: &str, expected: &str) -> bool {
    compare_fields(name, actual, expected, &[])
}

fn compare_fields(name: &str, actual: &str, expected: &str, frozen: &[usize]) -> bool {
    if asset_goldens::compare_with_frozen_fields(name, actual, expected, frozen) {
        return true;
    }
    if let Ok(dir) = std::env::var("WS6_VIEW_DIFF_DIR") {
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(format!("{dir}/{name}.actual"), actual).unwrap();
        std::fs::write(format!("{dir}/{name}.expected"), expected).unwrap();
    }
    let index = actual
        .bytes()
        .zip(expected.bytes())
        .position(|(a, b)| a != b)
        .unwrap_or(actual.len().min(expected.len()));
    eprintln!(
        "{name}: first difference at byte {index}; Rust {} bytes, Rails {} bytes",
        actual.len(),
        expected.len()
    );
    false
}

struct Tokens;
impl h::request_forgery::AuthenticityTokens for Tokens {
    fn global(&self) -> String {
        "GLOBAL".into()
    }
    fn for_form(&self, action: &str, method: &str) -> String {
        format!("{method}:{action}")
    }
}

fn render(template: &impl Template) -> String {
    h::request_forgery::rendering_with(
        h::request_forgery::RequestSecrets {
            tokens: Box::new(Tokens),
            csp_nonce: Some("NONCE".into()),
        },
        || template.render().unwrap(),
    )
}

#[test]
fn application_layout_matches_rails_in_every_state() {
    let env = include_str!("../../../parity/.env.reference");
    let secrets = rails_compat::Secrets::new(
        env.lines()
            .find_map(|line| line.strip_prefix("SECRET_KEY_BASE="))
            .unwrap(),
    );
    let signer = |parts: &[&str]| rails_compat::turbo::signed_stream_name(&secrets, parts);
    let asset = |path: &str| campfire_assets::asset_path(path);
    let styles = campfire_assets::stylesheet_link_tag_all(&[("data-turbo-track", "reload")]).html;
    let mut mismatches = Vec::new();
    for (name, user) in [
        ("application_signed_out", None),
        ("application_member", Some("JZ")),
        ("application_bot", Some("Bender Bot")),
        ("application_admin_full", Some("David")),
        ("application_everything_on", Some("Kevin")),
        ("application_searches_query", Some("David")),
    ] {
        let mut ctx = context(user, &asset, &signer, &styles);
        let full = matches!(name, "application_admin_full" | "application_everything_on");
        if name == "application_admin_full" {
            let preferences = &mut ctx.current_user.as_mut().unwrap().preferences;
            preferences.theme = Some("dark".into());
            preferences.text_size = Some("large".into());
            preferences.time_zone = Some("Eastern Time (US & Canada)".into());
            ctx.flash_notice = Some("Saved <b>it</b>".into());
        }
        if name == "application_everything_on" {
            let preferences = &mut ctx.current_user.as_mut().unwrap().preferences;
            preferences.theme = Some("light".into());
            preferences.text_size = Some("smaller".into());
            preferences.time_zone_explicit = true;
            preferences.tour_completed = false;
            preferences.google_drive = true;
            preferences.voice_mode = Some("push_to_talk".into());
            preferences.push_to_talk_key = Some("KeyT".into());
            preferences.notification_sounds = layouts::NotificationSounds {
                muted: true,
                quiet_hours: Some((1320, 420)),
                meeting_quiet: vec![
                    (1_790_000_000, 1_790_003_600),
                    (1_790_010_000, 1_790_012_000),
                ],
                ooo_quiet: vec![(0, 1_770_897_600), (1_790_100_000, 1_790_200_000)],
            };
            ctx.chrome.google_picker = Some(layouts::GooglePicker {
                client_id: "client-id.apps.googleusercontent.com".into(),
                api_key: "picker-api-key".into(),
                project_number: "123456789012".into(),
            });
            ctx.chrome.huddle_configured = true;
            ctx.flash_alert = Some("Couldn't save".into());
        }
        if name == "application_searches_query" {
            ctx.chrome.global_search_query = Some("pizza night".into());
        }
        let mut page =
            layouts::Application::new(&ctx, h::raw("<p class=\"golden-body\">Body</p>\n"));
        if full {
            page.head = h::raw("  <meta name=\"golden-head\" content=\"head\">\n");
            page.nav = h::raw("  <span class=\"golden-nav\">Nav</span>\n");
            page.sidebar = h::raw("  <div class=\"golden-sidebar\">Sidebar</div>\n");
            page.footer = h::raw("  <div class=\"golden-footer\">Footer</div>\n");
            page.member_panel = h::raw("  <aside class=\"golden-member-panel\"></aside>\n");
            page.thread_panel = h::raw("  <aside class=\"golden-thread-panel\"></aside>\n");
        }
        if name == "application_admin_full" {
            page.page_title = Some("Golden <Title> & Co".into());
            page.body_class = Some("golden-page".into());
        }
        if !compare(
            name,
            &render(&page),
            &fixture(&format!("layouts/{name}.html")),
        ) {
            mismatches.push(name);
        }
    }
    assert!(
        mismatches.is_empty(),
        "layout byte mismatches: {mismatches:?}"
    );
}

#[test]
fn public_and_mailer_layouts_match_rails() {
    let styles =
        h::raw(campfire_assets::stylesheet_link_tag(&["public"], &[("media", "all")]).html);
    for (name, title, description) in [
        ("public", Some("Golden"), None),
        ("public_described", None, Some("About <this> & that")),
    ] {
        let page = layouts::Public {
            page_title: title.map(str::to_string),
            page_description: description.map(str::to_string),
            public_stylesheet: h::raw(styles.0.clone()),
            content: h::raw("<p class=\"golden-body\">Body</p>\n"),
        };
        assert!(compare(
            name,
            &page.render().unwrap(),
            &fixture(&format!("layouts/{name}.html"))
        ));
    }
    assert!(compare(
        "mailer_html",
        &layouts::Mailer {
            content: h::raw("<p>Hello</p>\n")
        }
        .render()
        .unwrap(),
        &fixture("layouts/mailer_html.html")
    ));
    assert!(compare(
        "mailer_text",
        &layouts::TextMailer { content: "Hello\n" }.render().unwrap(),
        &fixture("layouts/mailer_text.txt")
    ));
}

#[test]
fn multi_select_bar_matches_rails_with_both_controls() {
    for (name, exit_button) in [
        ("shared_multi_select_bar", false),
        ("shared_multi_select_bar_exit", true),
    ] {
        assert!(compare(
            name,
            &render(&campfire_views::shared::MultiSelectBar { exit_button }),
            &fixture(&format!("partials/{name}.html"))
        ));
    }
}

#[test]
fn pwa_endpoints_match_rails() {
    let pages: Value = serde_json::from_str(&fixture("pages.json")).unwrap();
    let logo = facts()["account"]["logo_path"]
        .as_str()
        .unwrap()
        .to_string();
    let asset = |path: &str| campfire_assets::asset_path(path);
    let manifest = campfire_views::pwa::Manifest {
        account_name: Some("37signals".into()),
        logo_path_small: logo.replace("?v=", "?size=small&v="),
        logo_path: logo,
        base_url: "https://campfire.test".into(),
        asset_path: &asset,
    };
    assert!(compare(
        "pwa_manifest",
        &manifest.render().unwrap(),
        &fixture("pages/pwa_manifest.json")
    ));
    assert_eq!(pages["pwa_manifest"]["status"], 200);
    assert!(compare(
        "pwa_service_worker",
        campfire_views::pwa::SERVICE_WORKER_JS,
        &fixture("pages/pwa_service_worker.js")
    ));
}

#[test]
fn user_time_zone_uses_the_saved_rails_zone() {
    let zone = campfire_views::time::Zone::for_user(Some("Eastern Time (US & Canada)"));
    assert_eq!(zone.name(), "Eastern Time (US & Canada)");
    assert_eq!(zone.tz().iana_name(), Some("America/New_York"));
    assert_eq!(
        campfire_views::time::Zone::for_user(Some("Nowhere/Special")).name(),
        "UTC"
    );
}

#[test]
fn translations_and_avatar_helpers_match_rails() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    for (key, expected) in helpers["translations"].as_object().unwrap() {
        assert_eq!(
            h::translations_for(key).0,
            expected["translations_for"].as_str().unwrap(),
            "{key}"
        );
    }
    for row in helpers["initials"].as_array().unwrap() {
        assert_eq!(
            h::initials(row[0].as_str().unwrap()),
            row[1].as_str().unwrap()
        );
    }
    for row in helpers["avatar_colors"].as_array().unwrap() {
        assert_eq!(
            h::avatar_background_color(row[0].as_i64().unwrap()),
            row[1].as_str().unwrap()
        );
    }
}

#[test]
fn time_formats_and_local_tags_match_rails() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    for row in helpers["zone_lookups"].as_array().unwrap() {
        let actual = campfire_views::time::Zone::lookup(row[0].as_str().unwrap());
        assert_eq!(actual.as_ref().map(|zone| zone.name()), row[1].as_str());
        assert_eq!(
            actual.as_ref().and_then(|zone| zone.tz().iana_name()),
            row[2].as_str()
        );
    }
    for row in helpers["times"].as_array().unwrap() {
        let zone = campfire_views::time::Zone::lookup(row["zone"].as_str().unwrap()).unwrap();
        let instant = row["utc"].as_str().unwrap().parse().unwrap();
        assert_eq!(zone.iso8601(instant), row["iso8601"].as_str().unwrap());
        for key in ["to_s", "short", "long", "db", "number", "epoch"] {
            assert_eq!(
                zone.to_fs(instant, key),
                row[key].as_str().unwrap(),
                "{key}, {}",
                zone.name()
            );
        }
        for (format, expected) in row["strftime"].as_object().unwrap() {
            assert_eq!(
                zone.format(instant, format),
                expected.as_str().unwrap(),
                "{format}, {}",
                zone.name()
            );
        }
        assert_eq!(
            campfire_views::time::local_datetime_tag(&zone, instant, "time", h::attrs(), "").0,
            row["local_datetime_tag"].as_str().unwrap()
        );
        assert_eq!(
            campfire_views::time::local_datetime_tag(
                &zone,
                instant,
                "date",
                h::attrs().class("golden"),
                "then"
            )
            .0,
            row["local_datetime_tag_date"].as_str().unwrap()
        );
    }
}

#[test]
fn time_ago_matches_rails_at_rounding_and_leap_year_boundaries() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    let zone = campfire_views::time::Zone::utc();
    for row in helpers["distance_of_time"].as_array().unwrap() {
        let from = row["from"].as_str().unwrap().parse().unwrap();
        let to = row["to"].as_str().unwrap().parse().unwrap();
        assert_eq!(
            h::distance_of_time_in_words(&zone, from, to, false),
            row["words"].as_str().unwrap()
        );
        assert_eq!(
            h::distance_of_time_in_words(&zone, from, to, true),
            row["words_with_seconds"].as_str().unwrap()
        );
    }
}

#[test]
fn shared_icon_field_matches_rails_for_every_kind() {
    let asset = |path: &str| campfire_assets::asset_path(path);
    let signer = |_: &[&str]| String::new();
    let ctx = context(Some("David"), &asset, &signer, "");
    let github = h::AvatarIcon::Image {
        title: "GitHub".into(),
        url: "icons/brands/github.svg".into(),
        brand: true,
    };
    let emoji = h::AvatarIcon::Emoji {
        title: "Tada".into(),
        character: "🎉".into(),
    };
    for (kind, name, icon) in [
        ("none", None, None),
        ("unknown", Some("no_such_icon"), None),
        ("brand", Some("github"), Some(&github)),
        ("emoji", Some("tada"), Some(&emoji)),
    ] {
        let form = h::form_with("/golden").model("room").method("patch");
        let field = campfire_views::shared::IconField {
            ctx: &ctx,
            form: &form,
            scope: "room",
            icon_name: name,
            icon,
        };
        let actual = h::request_forgery::rendering_with(
            h::request_forgery::RequestSecrets {
                tokens: Box::new(Tokens),
                csp_nonce: None,
            },
            || form.wrap(&format!("\n  {}\n", field.render().unwrap())).0,
        );
        let name = format!("shared_icon_field_{kind}");
        assert!(compare(
            &name,
            &actual,
            &fixture(&format!("partials/{name}.html"))
        ));
    }
}

struct UserTokens(&'static str);
impl h::request_forgery::AuthenticityTokens for UserTokens {
    fn global(&self) -> String {
        self.0.into()
    }
    fn for_form(&self, action: &str, method: &str) -> String {
        format!("{}:{method}:{action}", self.0)
    }
}

#[test]
fn cached_legacy_boost_forms_never_share_a_viewers_token() {
    use campfire_views::{fragment_cache, messages};
    let asset = |path: &str| campfire_assets::asset_path(path);
    let signer = |_: &[&str]| String::new();
    let cache = fragment_cache::FragmentCache::new(1 << 20);
    let boost = messages::BoostView {
        reaction: None,
        id: 1,
        updated_at: "2026-02-10T12:00:00Z".parse().unwrap(),
        message_id: 2,
        content: "🎉".into(),
        all_emoji: true,
        booster: messages::UserView {
            id: 3,
            name: "Booster".into(),
            title: "Booster".into(),
            avatar_url: "/avatar".into(),
            icon: None,
        },
    };
    let mut outputs = Vec::new();
    for (user, token) in [("David", "DAVID-SESSION"), ("JZ", "JZ-SESSION")] {
        let ctx = context(Some(user), &asset, &signer, "");
        let html = h::request_forgery::rendering_with(
            h::request_forgery::RequestSecrets {
                tokens: Box::new(UserTokens(token)),
                csp_nonce: Some(token.into()),
            },
            || fragment_cache::with(&cache, || messages::boost(&ctx, &boost)),
        );
        assert!(
            !html.contains("authenticity_token"),
            "shared boost contains a request token"
        );
        assert!(!html.contains(token));
        outputs.push(html);
    }
    assert_eq!(outputs[0], outputs[1]);
}

#[test]
fn cached_button_to_can_explicitly_omit_its_authenticity_token() {
    let html = h::request_forgery::rendering_with(
        h::request_forgery::RequestSecrets {
            tokens: Box::new(Tokens),
            csp_nonce: None,
        },
        || {
            h::button_to(
                "/cached",
                h::attrs()
                    .method("delete")
                    .attr("authenticity_token", false),
                "Delete",
            )
            .0
        },
    );
    assert_eq!(
        html,
        "<form class=\"button_to\" method=\"post\" action=\"/cached\"><input type=\"hidden\" name=\"_method\" value=\"delete\" /><button type=\"submit\">Delete</button></form>"
    );
}

#[test]
fn cached_form_with_omits_tokens_but_keeps_method_override() {
    let html = h::request_forgery::rendering_with(
        h::request_forgery::RequestSecrets {
            tokens: Box::new(Tokens),
            csp_nonce: None,
        },
        || {
            h::form_with("/cached")
                .method("patch")
                .authenticity_token(false)
                .open()
                .0
        },
    );
    assert_eq!(
        html,
        "<form action=\"/cached\" accept-charset=\"UTF-8\" method=\"post\"><input type=\"hidden\" name=\"_method\" value=\"patch\" />"
    );
}

#[test]
fn custom_fragment_keys_match_pr148_rails() {
    use campfire_views::fragment_cache::keys::{self, MessageKey};
    let vectors: Value = serde_json::from_str(&fixture("cache_keys.json")).unwrap();
    let timestamp = |value: &Value| {
        value
            .as_str()
            .map(|value| value.parse::<jiff::Timestamp>().unwrap())
    };
    let stamps = |value: &Value| {
        value
            .as_array()
            .map(|values| values.iter().filter_map(timestamp).collect::<Vec<_>>())
            .unwrap_or_default()
    };
    assert_eq!(
        keys::PRESENTATION_CACHE_VERSION,
        vectors["presentation_cache_version"].as_i64().unwrap()
    );
    for row in vectors["quote_names_digests"].as_array().unwrap() {
        let names: Vec<(String, String)> = row[0]
            .as_array()
            .unwrap()
            .iter()
            .map(|pair| {
                (
                    pair[0].as_str().unwrap().into(),
                    pair[1].as_str().unwrap().into(),
                )
            })
            .collect();
        assert_eq!(keys::quote_names_inspect(&names), row[2].as_str().unwrap());
        assert_eq!(keys::quote_names_digest(&names), row[1].as_str().unwrap());
    }
    for row in vectors["message_with_pr_cards"].as_array().unwrap() {
        let data = MessageKey {
            record: row["message"].as_str().unwrap().into(),
            cards: stamps(&row["cards"]),
            embeds: row["embeds"]
                .as_array()
                .map(|embeds| {
                    embeds
                        .iter()
                        .map(|pair| (pair[0].as_i64().unwrap(), timestamp(&pair[1])))
                        .collect()
                })
                .unwrap_or_default(),
            has_pull_requests: row["has_pull_requests"].as_bool().unwrap_or(false),
            pr_threads_stamp: timestamp(&row["pr_threads_stamp"]),
            pins: stamps(&row["pins"]),
            thread_messages_count: row["thread_messages_count"].as_i64(),
            poll: timestamp(&row["poll"]),
            system_note: row["system_note"].as_bool().unwrap_or(false),
            streaming: row["streaming"].as_bool().unwrap_or(false),
            agent_steps: stamps(&row["agent_steps"]),
            quotes: row["quoted_sources"]
                .as_array()
                .map(|sources| {
                    sources
                        .iter()
                        .map(|source| {
                            (
                                timestamp(&source["edited_at"])
                                    .max(timestamp(&source["updated_at"]))
                                    .unwrap(),
                                source["creator"].as_str().unwrap().into(),
                                source["room"].as_str().map(str::to_owned),
                            )
                        })
                        .collect()
                })
                .unwrap_or_default(),
        };
        for zone in ["UTC", "Hawaii"] {
            let zone_model = campfire_views::time::Zone::lookup(zone).unwrap();
            let key = keys::message_with_pr_cards(&data);
            assert_eq!(
                keys::expand(&key, &zone_model),
                row["expanded"][zone]["key"].as_str().unwrap(),
                "{}, {zone}",
                row["label"]
            );
            assert_eq!(
                keys::fragment("messages/_message", "0123abcd", &key, &zone_model),
                row["expanded"][zone]["fragment"].as_str().unwrap()
            );
        }
    }
    for row in vectors["sidebar_membership"].as_array().unwrap() {
        let participants: Option<Vec<i64>> = row["participant_ids"]
            .as_array()
            .map(|values| values.iter().map(|value| value.as_i64().unwrap()).collect());
        let key = keys::sidebar_membership(
            row["membership"].as_str().unwrap(),
            participants.as_deref(),
            row["administrator"].as_bool().unwrap(),
        );
        assert_eq!(
            keys::expand(&key, &campfire_views::time::Zone::utc()),
            row["key"].as_str().unwrap()
        );
    }
}

#[test]
fn shared_avatar_links_and_first_paint_preloads_match_rails() {
    let asset = |path: &str| campfire_assets::asset_path(path);
    let signer = |_: &[&str]| String::new();
    let ctx = context(None, &asset, &signer, "");
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    for row in helpers["avatars"].as_array().unwrap() {
        let facts = facts();
        let user = &facts["users"][row["user"].as_str().unwrap()];
        let user = h::AvatarUser {
            id: user["id"].as_i64().unwrap(),
            title: row["title"].as_str().unwrap().into(),
            avatar_path: user["avatar_path"].as_str().unwrap().into(),
        };
        assert!(compare(
            "avatar",
            &h::avatar_tag(&ctx, &user, h::attrs().size(32).loading("lazy")).0,
            row["html"].as_str().unwrap()
        ));
    }
    let actual = h::request_forgery::rendering_with(
        h::request_forgery::RequestSecrets {
            tokens: Box::new(Tokens),
            csp_nonce: Some("NONCE".into()),
        },
        || h::first_paint_controller_preloads(&ctx).0,
    );
    assert!(compare(
        "first_paint_controller_preloads",
        &actual,
        &fixture("partials/first_paint_controller_preloads.html")
    ));
}

#[test]
fn byte_comparison_rejects_markup_whitespace_and_asset_changes() {
    let expected = fixture("layouts/application_signed_out.html");
    for (name, changed) in [
        (
            "injected_title",
            expected.replacen("Smartfire</title>", "Wrong</title>", 1),
        ),
        ("injected_space", format!("{expected} ")),
        (
            "injected_asset",
            expected.replacen("/assets/", "/wrong-assets/", 1),
        ),
    ] {
        assert_ne!(changed, expected, "injection must modify the fixture");
        assert!(!compare(name, &changed, &expected));
    }
}

#[test]
fn live_application_layout_rejects_dropped_reordered_stylesheets_and_wrong_digests() {
    let asset = |path: &str| campfire_assets::asset_path(path);
    let signer = |_: &[&str]| String::new();
    let styles = campfire_assets::stylesheet_link_tag_all(&[("data-turbo-track", "reload")]).html;
    let ctx = context(None, &asset, &signer, &styles);
    let page = layouts::Application::new(&ctx, h::raw("<p>Body</p>\n"));
    let actual = render(&page);
    assert!(compare("live layout", &actual, &actual));
    let tags: Vec<_> = styles.split_inclusive('>').take(2).collect();
    let people = campfire_assets::stylesheet_path("people");
    for (mutation, changed) in [
        ("drop stylesheet", actual.replacen(tags[0], "", 1)),
        (
            "reorder stylesheets",
            actual.replacen(
                &format!("{}{}", tags[0], tags[1]),
                &format!("{}{}", tags[1], tags[0]),
                1,
            ),
        ),
        (
            "wrong digest",
            actual.replacen(&people, "/assets/people-00000000.css", 1),
        ),
    ] {
        assert_ne!(changed, actual, "{mutation} must change the rendered page");
        assert!(!compare(mutation, &changed, &actual));
    }
}
