//! Byte comparisons with our Rails output, generated by reference-tools/views/core/run.sh.
use askama::Template;
use campfire_views::{AccountSummary, CurrentUser, Platform, ViewContext, helpers as h, layouts};
use serde_json::Value;

fn fixture(path: &str) -> String {
    std::fs::read_to_string(format!("{}/tests/golden/core/{path}", env!("CARGO_MANIFEST_DIR"))).unwrap()
}

fn facts() -> Value {
    serde_json::from_str(&fixture("facts.json")).unwrap()
}

fn context<'a>(user: Option<&str>, asset: &'a dyn Fn(&str) -> String, signer: &'a dyn Fn(&[&str]) -> String, styles: &'a str) -> ViewContext<'a> {
    let facts = facts();
    let current_user = user.map(|name| {
        let user = &facts["users"][name];
        CurrentUser {
            id: user["id"].as_i64().unwrap(),
            name: user["name"].as_str().unwrap().into(),
            administrator: user["administrator"].as_bool().unwrap(),
            bot: user["bot"].as_bool().unwrap(),
            avatar_url: user["avatar_path"].as_str().unwrap().into(),
            preferences: layouts::UserPreferences { tour_completed: user["tour_completed"].as_bool().unwrap(), ..Default::default() },
        }
    });
    let recent_searches = user.map(|name| facts["users"][name]["searches"].as_array().unwrap().iter().map(|search| layouts::RecentSearch {
        id: search["id"].as_i64().unwrap(), query: search["query"].as_str().unwrap().into(),
    }).collect()).unwrap_or_default();
    let env = include_str!("../../../parity/.env.reference");
    ViewContext {
        current_user,
        account: AccountSummary { name: "37signals".into(), logo_url: facts["account"]["logo_path"].as_str().unwrap().into(), has_logo: false },
        flash_notice: None, flash_alert: None,
        platform: Platform { mac: true, chrome: true, desktop: true, browser: "Chrome".into(), operating_system: "macOS".into(), ..Default::default() },
        vapid_public_key: Some(env.lines().find_map(|line| line.strip_prefix("VAPID_PUBLIC_KEY=")).unwrap().into()),
        asset_path: asset, importmap_tags: campfire_assets::javascript_importmap_tags(), stylesheet_tags: styles,
        custom_styles: None, cable_url: "/cable".into(), base_url: "http://campfire.test".into(), request_url: "http://campfire.test/".into(),
        referrer: None, last_room_visited_id: None, app_version: "parity".into(), signed_stream_name: signer,
        time_zone: campfire_views::time::Zone::utc(),
        chrome: layouts::Chrome { service_worker_auto_register: true, brand_icon_names: facts["brand_icon_names"].as_str().unwrap().split(',').map(str::to_string).collect(), recent_searches, ..Default::default() },
    }
}

fn compare(name: &str, actual: &str, expected: &str) -> bool {
    if actual == expected { return true; }
    if let Ok(dir) = std::env::var("WS6_VIEW_DIFF_DIR") {
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(format!("{dir}/{name}.actual"), actual).unwrap();
        std::fs::write(format!("{dir}/{name}.expected"), expected).unwrap();
    }
    let index = actual.bytes().zip(expected.bytes()).position(|(a, b)| a != b).unwrap_or(actual.len().min(expected.len()));
    eprintln!("{name}: first difference at byte {index}; Rust {} bytes, Rails {} bytes", actual.len(), expected.len());
    false
}

struct Tokens;
impl h::request_forgery::AuthenticityTokens for Tokens {
    fn global(&self) -> String { "GLOBAL".into() }
    fn for_form(&self, action: &str, method: &str) -> String { format!("{method}:{action}") }
}

fn render(template: &impl Template) -> String {
    h::request_forgery::rendering_with(h::request_forgery::RequestSecrets { tokens: Box::new(Tokens), csp_nonce: Some("NONCE".into()) }, || template.render().unwrap())
}

#[test]
fn application_layout_matches_rails_in_every_state() {
    let env = include_str!("../../../parity/.env.reference");
    let secrets = rails_compat::Secrets::new(env.lines().find_map(|line| line.strip_prefix("SECRET_KEY_BASE=")).unwrap());
    let signer = |parts: &[&str]| rails_compat::turbo::signed_stream_name(&secrets, parts);
    let asset = |path: &str| campfire_assets::asset_path(path);
    let styles = campfire_assets::stylesheet_link_tag_all(&[("data-turbo-track", "reload")]).html;
    let mut mismatches = Vec::new();
    for (name, user) in [
        ("application_signed_out", None), ("application_member", Some("JZ")), ("application_bot", Some("Bender Bot")),
        ("application_admin_full", Some("David")), ("application_everything_on", Some("Kevin")), ("application_searches_query", Some("David")),
    ] {
        let mut ctx = context(user, &asset, &signer, &styles);
        let full = matches!(name, "application_admin_full" | "application_everything_on");
        if name == "application_admin_full" {
            let preferences = &mut ctx.current_user.as_mut().unwrap().preferences;
            preferences.theme = Some("dark".into()); preferences.text_size = Some("large".into()); preferences.time_zone = Some("Eastern Time (US & Canada)".into());
            ctx.flash_notice = Some("Saved <b>it</b>".into());
        }
        if name == "application_everything_on" {
            let preferences = &mut ctx.current_user.as_mut().unwrap().preferences;
            preferences.theme = Some("light".into()); preferences.text_size = Some("smaller".into()); preferences.time_zone_explicit = true;
            preferences.tour_completed = false; preferences.google_drive = true; preferences.voice_mode = Some("push_to_talk".into()); preferences.push_to_talk_key = Some("KeyT".into());
            preferences.notification_sounds = layouts::NotificationSounds {
                muted: true, quiet_hours: Some((1320, 420)), meeting_quiet: vec![(1_790_000_000, 1_790_003_600), (1_790_010_000, 1_790_012_000)],
                ooo_quiet: vec![(0, 1_770_897_600), (1_790_100_000, 1_790_200_000)],
            };
            ctx.chrome.google_picker = Some(layouts::GooglePicker { client_id: "client-id.apps.googleusercontent.com".into(), api_key: "picker-api-key".into(), project_number: "123456789012".into() });
            ctx.chrome.huddle_configured = true; ctx.flash_alert = Some("Couldn't save".into());
        }
        if name == "application_searches_query" { ctx.chrome.global_search_query = Some("pizza night".into()); }
        let mut page = layouts::Application::new(&ctx, h::raw("<p class=\"golden-body\">Body</p>\n"));
        if full {
            page.head = h::raw("  <meta name=\"golden-head\" content=\"head\">\n");
            page.nav = h::raw("  <span class=\"golden-nav\">Nav</span>\n");
            page.sidebar = h::raw("  <div class=\"golden-sidebar\">Sidebar</div>\n");
            page.footer = h::raw("  <div class=\"golden-footer\">Footer</div>\n");
            page.member_panel = h::raw("  <aside class=\"golden-member-panel\"></aside>\n");
            page.thread_panel = h::raw("  <aside class=\"golden-thread-panel\"></aside>\n");
        }
        if name == "application_admin_full" { page.page_title = Some("Golden <Title> & Co".into()); page.body_class = Some("golden-page".into()); }
        if !compare(name, &render(&page), &fixture(&format!("layouts/{name}.html"))) { mismatches.push(name); }
    }
    assert!(mismatches.is_empty(), "layout byte mismatches: {mismatches:?}");
}

#[test]
fn public_and_mailer_layouts_match_rails() {
    let styles = h::raw(campfire_assets::stylesheet_link_tag(&["public"], &[("media", "all")]).html);
    for (name, title, description) in [("public", Some("Golden"), None), ("public_described", None, Some("About <this> & that"))] {
        let page = layouts::Public { page_title: title.map(str::to_string), page_description: description.map(str::to_string), public_stylesheet: h::raw(styles.0.clone()), content: h::raw("<p class=\"golden-body\">Body</p>\n") };
        assert!(compare(name, &page.render().unwrap(), &fixture(&format!("layouts/{name}.html"))));
    }
    assert!(compare("mailer_html", &layouts::Mailer { content: h::raw("<p>Hello</p>\n") }.render().unwrap(), &fixture("layouts/mailer_html.html")));
    assert!(compare("mailer_text", &layouts::TextMailer { content: "Hello\n" }.render().unwrap(), &fixture("layouts/mailer_text.txt")));
}

#[test]
fn multi_select_bar_matches_rails_with_both_controls() {
    for (name, exit_button) in [("shared_multi_select_bar", false), ("shared_multi_select_bar_exit", true)] {
        assert!(compare(name, &render(&campfire_views::shared::MultiSelectBar { exit_button }), &fixture(&format!("partials/{name}.html"))));
    }
}

#[test]
fn pwa_endpoints_match_rails() {
    let pages: Value = serde_json::from_str(&fixture("pages.json")).unwrap();
    let logo = facts()["account"]["logo_path"].as_str().unwrap().to_string();
    let asset = |path: &str| campfire_assets::asset_path(path);
    let manifest = campfire_views::pwa::Manifest { account_name: Some("37signals".into()), logo_path_small: logo.replace("?v=", "?size=small&v="), logo_path: logo, base_url: "https://campfire.test".into(), asset_path: &asset };
    assert!(compare("pwa_manifest", &manifest.render().unwrap(), &fixture("pages/pwa_manifest.json")));
    assert_eq!(pages["pwa_manifest"]["status"], 200);
    assert!(compare("pwa_service_worker", campfire_views::pwa::SERVICE_WORKER_JS, &fixture("pages/pwa_service_worker.js")));
}

#[test]
fn user_time_zone_uses_the_saved_rails_zone() {
    let zone = campfire_views::time::Zone::for_user(Some("Eastern Time (US & Canada)"));
    assert_eq!(zone.name(), "Eastern Time (US & Canada)");
    assert_eq!(zone.tz().iana_name(), Some("America/New_York"));
    assert_eq!(campfire_views::time::Zone::for_user(Some("Nowhere/Special")).name(), "UTC");
}

#[test]
fn translations_and_avatar_helpers_match_rails() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    for (key, expected) in helpers["translations"].as_object().unwrap() {
        assert_eq!(h::translations_for(key).0, expected["translations_for"].as_str().unwrap(), "{key}");
    }
    for row in helpers["initials"].as_array().unwrap() {
        assert_eq!(h::initials(row[0].as_str().unwrap()), row[1].as_str().unwrap());
    }
    for row in helpers["avatar_colors"].as_array().unwrap() {
        assert_eq!(h::avatar_background_color(row[0].as_i64().unwrap()), row[1].as_str().unwrap());
    }
}

#[test]
fn time_formats_and_local_tags_match_rails() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    for row in helpers["zone_lookups"].as_array().unwrap() {
        let actual = campfire_views::time::Zone::lookup(row[0].as_str().unwrap());
        assert_eq!(actual.as_ref().map(|zone| zone.name()), row[1].as_str());
        assert_eq!(actual.as_ref().and_then(|zone| zone.tz().iana_name()), row[2].as_str());
    }
    for row in helpers["times"].as_array().unwrap() {
        let zone = campfire_views::time::Zone::lookup(row["zone"].as_str().unwrap()).unwrap();
        let instant = row["utc"].as_str().unwrap().parse().unwrap();
        assert_eq!(zone.iso8601(instant), row["iso8601"].as_str().unwrap());
        for key in ["to_s", "short", "long", "db", "number", "epoch"] {
            assert_eq!(zone.to_fs(instant, key), row[key].as_str().unwrap(), "{key}, {}", zone.name());
        }
        for (format, expected) in row["strftime"].as_object().unwrap() {
            assert_eq!(zone.format(instant, format), expected.as_str().unwrap(), "{format}, {}", zone.name());
        }
        assert_eq!(campfire_views::time::local_datetime_tag(&zone, instant, "time", h::attrs(), "").0, row["local_datetime_tag"].as_str().unwrap());
        assert_eq!(campfire_views::time::local_datetime_tag(&zone, instant, "date", h::attrs().class("golden"), "then").0, row["local_datetime_tag_date"].as_str().unwrap());
    }
}

#[test]
fn time_ago_matches_rails_at_rounding_and_leap_year_boundaries() {
    let helpers: Value = serde_json::from_str(&fixture("helpers.json")).unwrap();
    let zone = campfire_views::time::Zone::utc();
    for row in helpers["distance_of_time"].as_array().unwrap() {
        let from = row["from"].as_str().unwrap().parse().unwrap();
        let to = row["to"].as_str().unwrap().parse().unwrap();
        assert_eq!(h::distance_of_time_in_words(&zone, from, to, false), row["words"].as_str().unwrap());
        assert_eq!(h::distance_of_time_in_words(&zone, from, to, true), row["words_with_seconds"].as_str().unwrap());
    }
}
