//! Complete row bytes generated by our Rails at d7c7de92; no HTML normalization.
use askama::Template;
use campfire_views::{ViewContext, users};
#[path = "support/context.rs"]
mod common;
use common::context;
use serde_json::Value;

fn fixtures() -> Vec<Value> {
    serde_json::from_str(include_str!("golden/sidebar/rows.json")).unwrap()
}
fn direct(row: &Value) -> users::SidebarDirect {
    users::SidebarDirect {
        room_id: row["room_id"].as_i64().unwrap(),
        unread: row["unread"].as_bool().unwrap(),
        updated_at_epoch: row["updated_at_epoch"].as_str().unwrap().into(),
        membership_id: row["membership_id"].as_i64().unwrap(),
        membership_updated_at: row["membership_updated_at"]
            .as_str()
            .unwrap()
            .parse()
            .unwrap(),
        label: row["label"].as_str().unwrap().into(),
        menu: serde_json::from_value(row["menu"].clone()).unwrap(),
        viewer_administrator: row["viewer_admin"].as_bool().unwrap(),
        huddle_participants: None,
        participant_ids: None,
        members: row["members"]
            .as_array()
            .unwrap()
            .iter()
            .map(|u| users::UserSummary {
                id: u["id"].as_i64().unwrap(),
                name: u["name"].as_str().unwrap().into(),
                avatar_path: u["avatar_path"].as_str().unwrap().into(),
                ..Default::default()
            })
            .collect(),
    }
}
fn shared(row: &Value) -> users::SidebarRoom {
    users::SidebarRoom {
        id: row["room_id"].as_i64().unwrap(),
        param_key: row["param_key"].as_str().unwrap().into(),
        name: row["room_name"].as_str().unwrap_or_default().into(),
        unread: row["unread"].as_bool().unwrap(),
        menu: serde_json::from_value(row["menu"].clone()).unwrap(),
        icon: row["icon_name"]
            .as_str()
            .and_then(campfire_views::messages::reactions::static_icon),
        huddle_participants: None,
    }
}
fn compare(row: &Value, actual: &str) -> bool {
    let name = row["name"].as_str().unwrap();
    let expected = row["html"].as_str().unwrap();
    if actual == expected {
        return true;
    }
    if let Ok(dir) = std::env::var("WS8BR_DIFF_DIR") {
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(format!("{dir}/{name}.actual"), actual).unwrap();
        std::fs::write(format!("{dir}/{name}.expected"), expected).unwrap();
    }
    let byte = actual
        .bytes()
        .zip(expected.bytes())
        .position(|(a, b)| a != b)
        .unwrap_or(actual.len().min(expected.len()));
    eprintln!(
        "{name}: first differing byte {byte}; actual {} bytes, Rails {} bytes",
        actual.len(),
        expected.len()
    );
    false
}
#[test]
fn shared_sidebar_rows_match_rails() {
    let asset = |name: &str| campfire_assets::asset_path(name);
    let signer = |_: &[&str]| String::new();
    let ctx = context(&asset, &signer);
    let mut failures = 0;
    for row in fixtures().into_iter().filter(|r| r["direct"] == false) {
        let actual = users::SidebarSharedPartial {
            ctx: &ctx,
            room: shared(&row),
        }
        .render()
        .unwrap();
        if !compare(&row, &actual) {
            failures += 1;
        }
    }
    assert_eq!(failures, 0, "shared row byte mismatches");
}
#[test]
fn direct_sidebar_rows_match_rails() {
    let asset = |name: &str| campfire_assets::asset_path(name);
    let signer = |_: &[&str]| String::new();
    let ctx = context(&asset, &signer);
    let mut failures = 0;
    for row in fixtures().into_iter().filter(|r| r["direct"] == true) {
        let actual = users::direct_room(&ctx, &direct(&row));
        if !compare(&row, &actual) {
            failures += 1;
        }
    }
    assert_eq!(failures, 0, "direct row byte mismatches");
}

#[test]
fn cached_rows_partition_administrator_and_huddle_participants() {
    let asset = |name: &str| campfire_assets::asset_path(name);
    let signer = |_: &[&str]| String::new();
    let ctx = context(&asset, &signer);
    let row = fixtures()
        .into_iter()
        .find(|r| r["name"] == "group_nonadmin_creator")
        .unwrap();
    let mut member = direct(&row);
    let store = campfire_views::fragment_cache::FragmentCache::new(1024 * 1024);
    let render = |row: &users::SidebarDirect| {
        campfire_views::fragment_cache::with(&store, || {
            users::cached_direct_room(&ctx, &users::SidebarDirectItem::from(row.clone()))
                .to_string()
        })
    };
    let ordinary = render(&member);
    assert!(ordinary.contains("data-menu-can-delete=\"false\""));
    member.viewer_administrator = true;
    member.menu.menu_can_delete = true;
    let admin = render(&member);
    assert!(admin.contains("data-menu-can-delete=\"true\""));
    assert_ne!(ordinary, admin);
    member.huddle_participants = Some("<span id=\"participant-one\"></span>".into());
    member.participant_ids = Some(vec![1]);
    assert!(render(&member).contains("participant-one"));
    member.huddle_participants = Some("<span id=\"participant-two\"></span>".into());
    member.participant_ids = Some(vec![2]);
    assert!(render(&member).contains("participant-two"));
    member.huddle_participants = None;
    member.participant_ids = None;
    assert_eq!(render(&member), admin);
    // A single-row broadcast bypasses the page collection cache as Rails does.
    member.label = "Changed without a collection-version bump".into();
    assert!(users::direct_room(&ctx, &member).contains(&member.label));
}

#[test]
fn rows_do_not_capture_request_tokens_nonces_or_actor_permissions() {
    use campfire_views::helpers::request_forgery::{
        AuthenticityTokens, RequestSecrets, rendering_with,
    };
    struct Tokens(&'static str);
    impl AuthenticityTokens for Tokens {
        fn global(&self) -> String {
            self.0.into()
        }
        fn for_form(&self, _: &str, _: &str) -> String {
            self.0.into()
        }
    }
    let asset = |name: &str| campfire_assets::asset_path(name);
    let signer = |_: &[&str]| String::new();
    let mut ctx = context(&asset, &signer);
    let row = fixtures()
        .into_iter()
        .find(|r| r["name"] == "group_nonadmin_creator")
        .unwrap();
    let member = direct(&row);
    let render = |ctx: &ViewContext, token: &'static str| {
        rendering_with(
            RequestSecrets {
                tokens: Box::new(Tokens(token)),
                csp_nonce: Some(token.into()),
            },
            || users::direct_room(ctx, &member),
        )
    };
    let detached = render(&ctx, "request-a");
    ctx.current_user = Some(campfire_views::CurrentUser {
        id: 999,
        name: "Actor admin".into(),
        administrator: true,
        bot: false,
        avatar_url: "actor-avatar".into(),
        preferences: Default::default(),
    });
    let actor = render(&ctx, "request-b");
    assert_eq!(detached, actor);
    assert_eq!(detached, row["html"].as_str().unwrap());
    for forbidden in [
        "request-a",
        "request-b",
        "authenticity_token",
        "csrf-token",
        "nonce=",
        "Actor admin",
        "actor-avatar",
    ] {
        assert!(!actor.contains(forbidden), "{forbidden} in broadcast row");
    }
    assert!(actor.contains("data-menu-can-delete=\"false\""));
}

#[test]
fn complete_sidebar_pages_match_rails() {
    use campfire_views::helpers::request_forgery::{
        AuthenticityTokens, RequestSecrets, rendering_with,
    };
    struct Tokens;
    impl AuthenticityTokens for Tokens {
        fn global(&self) -> String {
            "GLOBAL".into()
        }
        fn for_form(&self, action: &str, method: &str) -> String {
            format!("{method}:{action}")
        }
    }
    let asset = |name: &str| campfire_assets::asset_path(name);
    let signer = |_: &[&str]| String::new();
    let fixtures: Vec<Value> =
        serde_json::from_str(include_str!("golden/sidebar/page.json")).unwrap();
    let mut failures = 0;
    for row in fixtures {
        let mut ctx = context(&asset, &signer);
        ctx.account = campfire_views::AccountSummary {
            name: row["account_name"].as_str().unwrap().into(),
            logo_url: row["account_logo"].as_str().unwrap().into(),
            has_logo: row["has_logo"].as_bool().unwrap(),
        };
        let user = |u: &Value| users::UserSummary {
            id: u["id"].as_i64().unwrap(),
            name: u["name"].as_str().unwrap().into(),
            avatar_path: u["avatar_path"].as_str().unwrap().into(),
            ..Default::default()
        };
        let list = |key: &str| {
            row[key]
                .as_array()
                .unwrap()
                .iter()
                .map(shared)
                .collect::<Vec<_>>()
        };
        let categorized = list("categorized_memberships");
        let categories = row["room_categories"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| users::SidebarCategory {
                id: c["id"].as_i64().unwrap(),
                name: c["name"].as_str().unwrap().into(),
                collapsed: c["collapsed"].as_bool().unwrap(),
                rooms: categorized
                    .iter()
                    .filter(|r| r.menu.menu_category_id == c["id"].as_i64())
                    .cloned()
                    .collect(),
            })
            .collect();
        let page = users::SidebarShow {
            ctx: &ctx,
            current_user: user(&row["user"]),
            rooms_stream: String::new(),
            user_rooms_stream: String::new(),
            favorite_memberships: row["favorite_memberships"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    if r["param_key"] == "rooms_direct" {
                        users::SidebarItem::Direct(Box::new(direct(r)))
                    } else {
                        users::SidebarItem::Room(Box::new(shared(r)))
                    }
                })
                .collect(),
            categories,
            direct_memberships: row["direct_memberships"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| direct(r).into())
                .collect(),
            direct_placeholder_users: row["direct_placeholder_users"]
                .as_array()
                .unwrap()
                .iter()
                .map(user)
                .collect(),
            other_memberships: list("other_memberships"),
            voice_memberships: list("voice_memberships"),
            can_create_rooms: row["can_create_rooms"].as_bool().unwrap(),
        };
        let actual = rendering_with(
            RequestSecrets {
                tokens: Box::new(Tokens),
                csp_nonce: Some("NONCE".into()),
            },
            || page.as_content().render().unwrap(),
        );
        if !compare(&row, &actual) {
            failures += 1;
        }
    }
    assert_eq!(failures, 0, "full sidebar byte mismatches");
}
