//! Our `config/routes.rb`, for the app and its views: the route table the app dispatches on
//! ([`TABLE`]) and a function per named route that builds its path the way the Rails `*_path`
//! helper does (`campfire_routes::room(1)` is `room_path(1)`: the Rails name without `_path`).
//!
//! Both are generated by `build.rs` from `routes.json`, which `reference-tools/routes/routes.rb`
//! dumps from the reference app; regenerate it after a change to `config/routes.rb`. Path
//! parameters are escaped like Journey escapes them, `(.:format)` and query strings go through
//! [`NamedRoute::path_with`], and the `direct` routes (Ruby blocks, not Journey routes) are
//! written by hand below.

use std::fmt::{Display, Write as _};

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

/// One row of `bin/rails routes`.
#[derive(Debug)]
pub struct TableRoute {
    pub verb: &'static str,
    /// The Journey spec, e.g. `/rooms/:room_id/messages(.:format)`.
    pub spec: &'static str,
    /// `controller#action`.
    pub endpoint: &'static str,
    pub name: Option<&'static str>,
    /// `defaults:` other than the controller and action.
    pub defaults: &'static [(&'static str, &'static str)],
    pub action: ActionStatus,
}

/// Whether the reference can run a route's action.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActionStatus {
    /// The controller defines the action method.
    Defined,
    /// No method, but a template, which `ActionController::ImplicitRender` renders.
    Implicit,
    /// Declared by `resources` but not defined: `AbstractController::ActionNotFound`, a 404.
    ActionNotFound,
    /// The controller constant doesn't load: a 500.
    MissingController,
}

/// A named route's path, split where arguments go.
#[derive(Debug)]
pub struct NamedRoute {
    pub name: &'static str,
    pub spec: &'static str,
    pub segments: &'static [Segment],
    /// `defaults: { format: :json }`: asking for this format adds no suffix, as in Rails.
    pub default_format: Option<&'static str>,
}

#[derive(Debug)]
pub enum Segment {
    Literal(&'static str),
    /// `:param`, escaped as a path segment (`/` becomes `%2F`).
    Param,
    /// `*glob`, escaped as a path (`/` stays).
    Glob,
}

impl NamedRoute {
    /// The path for these arguments, in the order the Rails helper takes them positionally.
    pub fn path(&self, args: &[&dyn Display]) -> String {
        let mut args = args.iter();
        let mut path = String::new();
        for segment in self.segments {
            match segment {
                Segment::Literal(literal) => path.push_str(literal),
                Segment::Param | Segment::Glob => {
                    let arg = args.next().unwrap_or_else(|| panic!("{}_path: missing argument", self.name));
                    let value = arg.to_string();
                    path.push_str(&escape(&value, matches!(segment, Segment::Glob)));
                }
            }
        }
        assert!(args.next().is_none(), "{}_path: too many arguments", self.name);
        path
    }

    /// `name_path(*args, format: format, **query)`. `None` query values are dropped, as Rails
    /// drops nil options.
    pub fn path_with(&self, args: &[&dyn Display], format: Option<&str>, query: &[(&str, Option<&str>)]) -> String {
        let mut path = self.path(args);
        if let Some(format) = format
            && self.spec.ends_with("(.:format)")
            && Some(format) != self.default_format
        {
            path.push('.');
            path.push_str(&escape(format, false));
        }
        with_query(path, query)
    }
}

/// `path?` + `Hash#to_query` of the pairs whose value isn't `None`: each `key=value` CGI-escaped,
/// the pairs sorted, joined with `&`. No `?` when nothing is left.
pub fn with_query(mut path: String, query: &[(&str, Option<&str>)]) -> String {
    let mut pairs: Vec<String> = query
        .iter()
        .filter_map(|(key, value)| Some(format!("{}={}", cgi_escape(key), cgi_escape((*value)?))))
        .collect();
    if pairs.is_empty() {
        return path;
    }
    pairs.sort();
    path.push('?');
    path.push_str(&pairs.join("&"));
    path
}

/// `Journey::Router::Utils.escape_segment` (and `escape_path` when `/` is allowed): everything
/// but RFC 3986's unreserved and sub-delims characters, `:` and `@` is percent-encoded.
pub fn escape(value: &str, keep_slash: bool) -> String {
    let mut escaped = String::with_capacity(value.len());
    for byte in value.bytes() {
        let keep = byte.is_ascii_alphanumeric()
            || b"-._~!$&'()*+,;=:@".contains(&byte)
            || (keep_slash && byte == b'/');
        if keep {
            escaped.push(byte as char);
        } else {
            write!(escaped, "%{byte:02X}").unwrap();
        }
    }
    escaped
}

/// `CGI.escape`: letters, digits and `_.-~` stay, a space becomes `+`, the rest is encoded.
pub fn cgi_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b' ' => escaped.push('+'),
            b if b.is_ascii_alphanumeric() || b"_.-~".contains(&b) => escaped.push(b as char),
            b => write!(escaped, "%{b:02X}").unwrap(),
        }
    }
    escaped
}

/// `direct :fresh_user_avatar`: `user_avatar_path(user.avatar_token, v: user.updated_at.to_fs(:number))`.
pub fn fresh_user_avatar(avatar_token: impl Display, updated_at_number: impl Display) -> String {
    USER_AVATAR.path_with(&[&avatar_token], None, &[("v", Some(&updated_at_number.to_string()))])
}

/// `direct :fresh_account_logo`: `account_logo_path(v: Current.account&.updated_at&.to_fs(:number),
/// size: options[:size])`. `v` is `None` without an account.
pub fn fresh_account_logo(v: Option<&str>, size: Option<&str>) -> String {
    ACCOUNT_LOGO.path_with(&[], None, &[("v", v), ("size", size)])
}

#[cfg(test)]
mod tests;
