//! Direct consumer contracts for WS14g, generated by pinned Event/Attendance saves.
use super::*;
use crate::broadcasts::Partial;
use serde_json::{Value, json};

fn vectors() -> Value {
    serde_json::from_str(include_str!(
        "../../models/calendar_event/calendar_api.json"
    ))
    .unwrap()
}

fn yes(spec: &Value, key: &str) -> bool {
    spec[key].as_bool().unwrap_or(false)
}

fn stamp(time: Timestamp) -> String {
    format!(
        "{}.{:06}Z",
        time.jiff().strftime("%Y-%m-%dT%H:%M:%S"),
        time.subsec_microsecond()
    )
}

fn assert_result(result: Result<()>, expected: &Value, name: &str) {
    let (kind, errors) = match result {
        Ok(()) => ("ok", vec![]),
        Err(Error::RecordInvalid(e)) => ("ActiveRecord::RecordInvalid", e.full_messages()),
        Err(Error::Sqlite(_)) => ("ActiveRecord::StatementInvalid", vec![]),
        Err(Error::Other(e)) if e.contains("not a valid response") => ("ArgumentError", vec![]),
        Err(Error::Other(e)) if e == "outer rollback" => ("RuntimeError", vec![]),
        Err(e) => panic!("{name}: unexpected {e}"),
    };
    assert_eq!(kind, expected["result"].as_str().unwrap(), "{name}");
    assert_eq!(json!(errors), expected["errors"], "{name}");
}

fn callbacks(t: &TestDb, rows: &[CalendarEvent]) -> (Value, Value) {
    let mut jobs = vec![];
    let mut cards = vec![];
    for event in t.events() {
        if let Event::Job(job) = &event
            && job.class.starts_with("Calendar::")
        {
            let event_id = job.arguments["event_id"].as_i64().unwrap();
            let key = format!(
                "event-{}",
                rows.iter().position(|e| e.id == event_id).unwrap()
            );
            let args = if job.class == "Calendar::SyncEntryJob" {
                json!([key, job.arguments["user_id"]])
            } else {
                json!([key])
            };
            jobs.push(json!([job.class, args]));
        }
        if let Some(crate::broadcasts::Broadcast::Turbo(frame)) = event.as_broadcast()
            && matches!(frame.partial, Some(Partial::EventCards { .. }))
        {
            assert_eq!(frame.action, crate::broadcasts::TurboAction::Replace);
            cards.push(json!({
                "stream": frame.streamables.iter().map(|s|s.to_param()).collect::<Vec<_>>().join(":"),
                "target": frame.target, "action": "replace", "maintain_scroll": frame.maintain_scroll
            }));
        }
    }
    (json!(jobs), json!(cards))
}

#[test]
fn calendar_api_meet_link_rejects_an_ineligible_organizer_without_writes() {
    let t = frozen();
    let event = create(&t);
    let eid = event.id;
    t.write(move |tx| {
        tx.conn().execute(
            "DELETE FROM memberships WHERE room_id=? AND user_id=?",
            params![event.room_id, event.organizer_id],
        )?;
        Ok(())
    });
    t.sink.take();
    assert!(matches!(
        t.try_write(move |tx| CalendarEvent::save_meet_link(
            tx,
            eid,
            Some("https://meet.example.test/fixture".into())
        )),
        Err(Error::RecordInvalid(_))
    ));
    assert_eq!(t.read(|c| CalendarEvent::find(c, eid)), event);
    assert!(t.events().is_empty());
}

#[test]
fn calendar_api_responses_match_rails_rows_and_commit_callbacks() {
    for case in vectors()["respond"].as_array().unwrap() {
        let spec = &case["spec"];
        let name = spec["name"].as_str().unwrap();
        let t = frozen();
        let head = if yes(spec, "series") {
            series(&t)
        } else {
            create(&t)
        };
        let rows = t.read(|c| head.series_events(c));
        let user = id(spec["user"].as_str().unwrap_or("jason"));
        if let Some(response) = spec["existing"].as_str() {
            for row in &rows {
                let eid = row.id;
                let response = response.to_string();
                t.write(move |tx| CalendarEvent::respond(tx, eid, user, &response, false));
            }
        }
        if yes(spec, "distinct") {
            let eid = rows.last().unwrap().id;
            t.write(move |tx| CalendarEvent::respond(tx, eid, user, "declined", false));
        }
        if let Some(index) = spec["cancelled"].as_u64() {
            let eid = rows[index as usize].id;
            t.write(move |tx| {
                tx.conn().execute(
                    "UPDATE events SET cancelled_at=? WHERE id=?",
                    params![tx.now(), eid],
                )?;
                Ok(())
            });
        }
        if yes(spec, "nonmember") {
            t.write(move |tx| {
                tx.conn().execute(
                    "DELETE FROM memberships WHERE room_id=? AND user_id=?",
                    params![head.room_id, user],
                )?;
                Ok(())
            });
        }
        if yes(spec, "fail") {
            let follower = rows[1].id;
            t.write(move |tx| {
                tx.conn().execute_batch(&format!("CREATE TEMP TRIGGER reject_calendar_api BEFORE INSERT ON event_attendances WHEN NEW.event_id={follower} AND NEW.user_id={user} BEGIN SELECT RAISE(ABORT,'calendar api unavailable'); END"))?;
                Ok(())
            });
        }
        t.sink.take();
        t.travel(60);
        let spec = spec.clone();
        let eid = rows[spec["index"].as_u64().unwrap_or(0) as usize].id;
        let sink = t.sink.clone();
        let result = t.try_write(move |tx| {
            CalendarEvent::respond(
                tx,
                eid,
                user,
                spec["response"].as_str().unwrap_or("maybe"),
                yes(&spec, "future"),
            )?;
            if yes(&spec, "twice") {
                CalendarEvent::respond(tx, eid, user, "declined", true)?;
            }
            if yes(&spec, "destroy") {
                CalendarEvent::find(tx.conn(), eid)?.destroy(tx)?;
            }
            assert!(sink.events().is_empty(), "callbacks must wait for commit");
            if yes(&spec, "rollback") {
                return Err(Error::Other("outer rollback".into()));
            }
            Ok(())
        });
        assert_result(result, case, name);
        let state: Vec<_> = rows
            .iter()
            .map(|e| {
                t.read(|c| EventAttendance::find_for(c, e.id, user))
                    .map(|a| json!({"response":a.response,"updated_at":stamp(a.updated_at)}))
            })
            .collect();
        assert_eq!(json!(state), case["state"], "{name}");
        let (jobs, cards) = callbacks(&t, &rows);
        assert_eq!(jobs, case["jobs"], "{name}");
        assert_eq!(cards, case["cards"], "{name}");
    }
}

#[test]
fn calendar_api_meet_link_saves_match_rails_validation_and_card_callbacks() {
    for case in vectors()["meet_link"].as_array().unwrap() {
        let spec = &case["spec"];
        let name = spec["name"].as_str().unwrap();
        let t = frozen();
        let mut a = attrs(&t);
        a.meet_link_requested = spec["requested"].as_bool().unwrap_or(true);
        let event = t.write(move |tx| CalendarEvent::create(tx, a));
        let eid = event.id;
        let spec = spec.clone();
        let room_id = event.room_id;
        let key = format!("api-{name}");
        t.write(move |tx| {
            if spec.get("existing").is_some() { tx.conn().execute("UPDATE events SET meet_link=? WHERE id=?",params![spec["existing"].as_str(),eid])?; }
            if yes(&spec,"cancelled") {tx.conn().execute("UPDATE events SET cancelled_at=? WHERE id=?",params![tx.now(),eid])?;}
            match spec["invalid"].as_str() {
                Some("title")=>{tx.conn().execute("UPDATE events SET title='' WHERE id=?",[eid])?;},
                Some("ends_at")=>{tx.conn().execute("UPDATE events SET ends_at=starts_at WHERE id=?",[eid])?;},
                Some("time_zone")=>{tx.conn().execute("UPDATE events SET time_zone='Mars/Olympus' WHERE id=?",[eid])?;},
                _=>(),
            }
            tx.conn().execute("UPDATE messages SET client_message_id=? WHERE id IN (SELECT message_id FROM event_references WHERE event_id=?)",params![format!("{key}-announcement"),eid])?;
            if yes(&spec,"nonmember") {
                tx.conn().execute("DELETE FROM memberships WHERE room_id=? AND user_id=?",params![room_id,id("david")])?;
            } else {
                crate::Message::create(tx,crate::NewMessage {room_id,creator_id:id("david"),client_message_id:Some(format!("{key}-extra")),markdown_source:Some(format!("http://example.com/rooms/{room_id}/events/{eid}")),..Default::default()})?;
            }
            if yes(&spec,"fail") {tx.conn().execute_batch("CREATE TEMP TRIGGER reject_calendar_api BEFORE UPDATE OF meet_link ON events BEGIN SELECT RAISE(ABORT,'calendar api unavailable'); END")?;}
            Ok(())
        });
        t.sink.take();
        t.travel(60);
        let spec = case["spec"].clone();
        let sink = t.sink.clone();
        let result = t.try_write(move |tx| {
            CalendarEvent::save_meet_link(tx, eid, spec["link"].as_str().map(str::to_string))?;
            if yes(&spec, "twice") {
                CalendarEvent::save_meet_link(
                    tx,
                    eid,
                    Some(
                        spec["second"]
                            .as_str()
                            .unwrap_or("https://meet.example.test/second")
                            .into(),
                    ),
                )?;
            }
            assert!(sink.events().is_empty(), "callbacks must wait for commit");
            if yes(&spec, "rollback") {
                return Err(Error::Other("outer rollback".into()));
            }
            Ok(())
        });
        assert_result(result, case, name);
        let saved = t.read(|c| CalendarEvent::find(c, eid));
        assert_eq!(
            json!({"meet_link":saved.meet_link,"updated_at":stamp(saved.updated_at),"needs_meet_link":saved.needs_meet_link()}),
            case["state"],
            "{name}"
        );
        let (jobs, cards) = callbacks(&t, &[event]);
        assert_eq!(jobs, case["jobs"], "{name}");
        assert_eq!(cards, case["cards"], "{name}");
    }
}
